"use client";

export default function Section9() {
  return (
    <section
      id="s9"
      className="scroll-mt-24 border-b border-gray-200 pb-24"
    >

      {/* HEADER */}
      <div className="relative p-12 rounded-2xl bg-[#F8FAFC] border border-gray-200 shadow-lg overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#0B3A63]/8 to-[#15B097]/15 pointer-events-none"></div>

        <h2 className="text-4xl md:text-5xl font-extrabold text-[#0B3A63] relative z-10">
          9. Sample PDF Output
        </h2>

        <p className="text-lg text-gray-700 max-w-4xl mt-6 leading-relaxed relative z-10">
          Below is a real demonstration PDF generated by Certif-Scope, including standard
          CO₂ indicators, structured breakdowns, dataset references, PDF/A formatting and
          embedded SHA-256 cryptographic fingerprint. This file is identical to what banks,
          procurement teams and insurers will receive.
        </p>

        {/* PDF DOWNLOAD BUTTON */}
        <div className="mt-8 relative z-10">
          <a
            href="/demo/certif-scope-demo.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-block bg-[#0B3A63] text-white px-6 py-3 rounded-lg font-semibold shadow-md hover:bg-[#092c4a] transition"
          >
            Download Demo PDF
          </a>
        </div>
      </div>


      {/* PDF IMAGE PREVIEW */}
      <div className="mt-16 p-8 bg-white border border-gray-200 rounded-xl shadow-md">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Preview (Page 1 of the actual PDF)
        </h3>

        <img
          src="/demo/pdf-preview-1.png"
          alt="Certif-Scope PDF Preview"
          className="rounded-lg border shadow-md w-full"
        />
      </div>


      {/* XMP METADATA CSV TABLE */}
      <div className="mt-20 p-10 bg-[#F8FAFC] border border-[#15B097]/40 rounded-xl shadow-sm">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Embedded XMP Metadata (CSV Extract)
        </h3>

        <p className="text-gray-700 text-sm leading-relaxed mb-4">
          The table below shows the actual XMP metadata fields embedded in the PDF file.
          These can be extracted automatically by audit systems and verification tools.
        </p>

        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse border border-gray-300">
            <thead className="bg-white">
              <tr>
                <th className="border border-gray-300 p-2 font-semibold">Field</th>
                <th className="border border-gray-300 p-2 font-semibold">Value (example)</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border border-gray-300 p-2">dc:title</td>
                <td className="border border-gray-300 p-2">"Certif-Scope Attestation"</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">pdf:Producer</td>
                <td className="border border-gray-300 p-2">"Certif-Scope Engine v1.0"</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">xmp:CreateDate</td>
                <td className="border border-gray-300 p-2">"2024-01-30T10:45:00Z"</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">xmp:ModifyDate</td>
                <td className="border border-gray-300 p-2">"2024-01-30T10:45:00Z"</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">xmp:SHA256</td>
                <td className="border border-gray-300 p-2">"a3b1c42f8e91d0a9e9b56c27a9d913e6b26f82fb..."</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">pdfaid:Part</td>
                <td className="border border-gray-300 p-2">"1" (PDF/A Level A)</td>
              </tr>
              <tr>
                <td className="border border-gray-300 p-2">pdfaid:Conformance</td>
                <td className="border border-gray-300 p-2">"A"</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>


      {/* RETURN BUTTON */}
      <div className="mt-12 text-right">
        <a
          href="#top"
          className="inline-block text-sm px-4 py-2 rounded-md border border-[#0B3A63] text-[#0B3A63] hover:bg-[#0B3A63] hover:text-white transition-colors"
        >
          Back to summary
        </a>
      </div>

    </section>
  );
      }
