"use client";

export default function Section9() {
  return (
    <section
      id="s9"
      data-section="s9"
      className="scroll-mt-24 border-b border-gray-200 pb-24"
    >

      {/* HEADER */}
      <div className="relative p-12 rounded-2xl bg-[#F8FAFC] border border-gray-200 shadow-lg overflow-hidden">
        <div
          className="absolute inset-0 bg-gradient-to-br from-[#0B3A63]/8 to-[#15B097]/15 pointer-events-none"
          aria-hidden="true"
        ></div>

        <h2
          className="text-4xl md:text-5xl font-extrabold text-[#0B3A63] relative z-10"
          data-i18n="s9.title"
        >
          Sample PDF Output
        </h2>

        <p
          className="text-lg text-gray-700 max-w-4xl mt-6 leading-relaxed relative z-10"
          data-i18n="s9.intro"
        >
          Below is a demonstration PDF generated by Certif-Scope. It illustrates the standardized
          layout, category breakdowns, dataset references, and the embedded SHA-256 integrity hash.
          This preview represents the format typically used by procurement teams, banks, insurers
          and institutional reviewers. It is not a CSRD/ESRS climate report nor an audited GHG
          inventory; it is an indicative, spend-based attestation designed for screening workflows.
        </p>

        {/* PDF DOWNLOAD BUTTON */}
        <div className="mt-8 relative z-10">
          <a
            href="/demo/certif-scope-demo.pdf"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Download sample Certif-Scope PDF"
            data-i18n="s9.download"
            className="inline-block bg-[#0B3A63] text-white px-6 py-3 rounded-lg font-semibold shadow-md hover:bg-[#092c4a] transition"
          >
            Download Demo PDF
          </a>
        </div>
      </div>

      {/* PDF IMAGE PREVIEW */}
      <div className="mt-16 p-8 bg-white border border-gray-200 rounded-xl shadow-md">
        <h3
          className="text-2xl font-semibold text-[#0B3A63] mb-4"
          data-i18n="s9.preview.title"
        >
          Preview — Page 1 of Sample Attestation
        </h3>

        <img
          src="/demo/pdf-preview-1.png"
          alt="Preview of the Certif-Scope CO₂e attestation showing total CO₂e, category breakdown, dataset references and verification hash"
          className="rounded-lg border shadow-md w-full"
          data-i18n="s9.preview.image"
        />
      </div>

      {/* XMP METADATA TABLE */}
      <div
        className="mt-20 p-10 bg-[#F8FAFC] border border-[#15B097]/40 rounded-xl shadow-sm"
        data-i18n="s9.xmp.block"
      >
        <h3
          className="text-2xl font-semibold text-[#0B3A63] mb-4"
          data-i18n="s9.xmp.title"
        >
          Embedded XMP Metadata (Extract Example)
        </h3>

        <p
          className="text-gray-700 text-sm leading-relaxed mb-4"
          data-i18n="s9.xmp.text"
        >
          These metadata fields are embedded automatically inside the PDF using the XMP standard.
          They enable offline verification, audit traceability, compatibility with archival workflows
          and provide deterministic information about the dataset version and hash value used.
        </p>

        <div className="overflow-x-auto">
          <table className="w-full text-sm border-collapse border border-gray-300">
            <thead className="bg-white">
              <tr>
                <th className="border border-gray-300 p-2 font-semibold" data-i18n="s9.xmp.col1">
                  Field
                </th>
                <th className="border border-gray-300 p-2 font-semibold" data-i18n="s9.xmp.col2">
                  Example Value
                </th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td className="border border-gray-300 p-2">dc:title</td>
                <td className="border border-gray-300 p-2">"Certif-Scope Attestation"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">pdf:Producer</td>
                <td className="border border-gray-300 p-2">"Certif-Scope Engine v1.0"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">xmp:CreateDate</td>
                <td className="border border-gray-300 p-2">"2024-01-30T10:45:00Z"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">xmp:ModifyDate</td>
                <td className="border border-gray-300 p-2">"2024-01-30T10:45:00Z"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">xmp:SHA256</td>
                <td className="border border-gray-300 p-2">"example-hash-value-123abc..."</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">xmp:DatasetVersion</td>
                <td className="border border-gray-300 p-2">"ADEME-2024.01"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">xmp:GWPVersion</td>
                <td className="border border-gray-300 p-2">"IPCC AR6"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">pdfaid:Part</td>
                <td className="border border-gray-300 p-2">"2"</td>
              </tr>

              <tr>
                <td className="border border-gray-300 p-2">pdfaid:Conformance</td>
                <td className="border border-gray-300 p-2">"B"</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      {/* RETURN BUTTON */}
      <div className="mt-12 text-right">
        <a
          href="#top"
          data-i18n="s9.return"
          className="inline-block text-sm px-4 py-2 rounded-md border border-[#0B3A63] text-[#0B3A63] hover:bg-[#0B3A63] hover:text-white transition-colors"
        >
          Back to summary
        </a>
      </div>

    </section>
  );
      }
