export default function Section3() {
  return (
    <section
      id="s3"
      className="
        scroll-mt-24
        bg-white 
        dark:bg-gray-900
        p-14 
        rounded-2xl
        border border-gray-200 dark:border-gray-800
        shadow-[0_6px_24px_rgba(0,0,0,0.06)]
      "
    >
      {/* HEADER */}
      <div className="mb-12">
        <h2 className="text-4xl font-extrabold text-[#0B3A63] tracking-tight mb-4">
          Why the Product Exists
        </h2>

        <p className="text-lg text-gray-700 dark:text-gray-300 max-w-3xl leading-relaxed">
          Certif-Scope was created to solve a growing structural issue in European B2B workflows:
          SMEs are increasingly required to provide standardized CO₂ indicators, yet existing
          solutions are slow, expensive, inconsistent and rarely accepted by institutions.
        </p>
      </div>

      {/* MAIN CONTENT */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        
        {/* LEFT COLUMN LIST – PROBLEMS */}
        <div className="space-y-8">
          <div className="border-l-4 border-[#15B097] pl-6">
            <h3 className="text-2xl font-semibold text-[#0B3A63] mb-2">
              1) Rising Regulatory Pressure
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Banks, insurers, procurement departments and public institutions now require clear
              CO₂ indicators during onboarding, supplier validation, financing requests or ESG screenings.
              SMEs are expected to comply, but lack tools to do so instantly.
            </p>
          </div>

          <div className="border-l-4 border-[#0B3A63] pl-6">
            <h3 className="text-2xl font-semibold text-[#0B3A63] mb-2">
              2) Carbon Assessments Are Slow & Expensive
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Traditional environmental assessments can take several weeks, involve consultants,
              and cost hundreds to thousands of euros—making them inaccessible for many SMEs.
            </p>
          </div>

          <div className="border-l-4 border-[#15B097] pl-6">
            <h3 className="text-2xl font-semibold text-[#0B3A63] mb-2">
              3) Non-Standardized Outputs Are Rejected
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">
              Many carbon reports fail because they use inconsistent formats, unverified data,
              and lack the transparency required by institutional reviewers.
            </p>
          </div>
        </div>

        {/* RIGHT COLUMN — ILLUSTRATIVE INFO BLOCKS */}
        <div className="space-y-10">

          <div className="p-8 rounded-xl bg-[#F8FAFC] dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-sm">
            <h3 className="text-xl font-semibold text-[#0B3A63] mb-3">
              “Instant” is Now a Real Requirement
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">
              Procurement and financial institutions increasingly automate onboarding. A supplier
              needing 2–3 weeks to provide a carbon indicator is now a bottleneck. Certif-Scope
              solves this by delivering a verified document in seconds.
            </p>
          </div>

          <div className="p-8 rounded-xl bg-white dark:bg-gray-800 border border-[#15B097]/30 shadow">
            <h3 className="text-xl font-semibold text-[#15B097] mb-3">
              A Single Accepted Format Across Europe
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">
              Certif-Scope provides a unified, review-ready structure compatible with European ESG
              procurement workflows, financial due-diligence requirements and institutional templates.
            </p>
          </div>

          <div className="p-8 rounded-xl bg-[#F8FAFC] dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-sm">
            <h3 className="text-xl font-semibold text-[#0B3A63] mb-3">
              Built to Be Machine-Readable
            </h3>
            <p className="text-gray-600 dark:text-gray-400 text-sm">
              Attestations generated by Certif-Scope are structured so automated systems and AI-based
              compliance tools can parse and validate the content without manual review.
            </p>
          </div>

        </div>
      </div>

      {/* CTA BLOCK */}
      <div className="mt-14 p-8 rounded-xl bg-[#0B3A63] text-white shadow-lg">
        <h3 className="text-2xl font-bold mb-3">The Real Problem Certif-Scope Solves</h3>
        <p className="text-white/90 text-sm leading-relaxed max-w-3xl">
          Certif-Scope eliminates delays, cost barriers and rejection risk by providing 
          institutional-grade CO₂ indicators on demand—instantly, transparently and with 
          cryptographic verification. This transforms environmental compliance from a 
          multi-week process into a frictionless step in supplier onboarding.
        </p>
      </div>

      {/* RETURN BUTTON (UNIFORM) */}
      <div className="mt-12">
        <a
          href="#top"
          className="
            inline-flex items-center px-4 py-2 
            text-sm font-medium 
            text-[#0B3A63]
            border border-[#0B3A63]/25 
            rounded-md 
            hover:bg-[#0B3A63]/10
            transition
          "
        >
          Back to Summary
        </a>
      </div>
    </section>
  );
}
