export const formCopy = {
  en: {
    title: "Generate an indicative CO₂e attestation for your business",
    intro:
      "Prepare a standardised PDF from seven categories of annual external expenditure. Confirm that your recipient accepts this indicative method before ordering.",
    steps: ["Company", "Expenditure", "Review"],
    stepTitles: [
      "Company and context",
      "Annual expenditure",
      "Review before payment",
    ],
    step: "Step",
    of: "of",
    company: "Company / legal entity name",
    sector: "Main activity sector",
    selectSector: "Select your activity sector",
    identifier: "Company identifier (optional)",
    year: "Reference year",
    country: "Main country",
    language: "Attestation language",
    countries: ["France", "Germany", "Other EU"],
    next: "Continue to expenditure",
    back: "Back",
    review: "Review my estimate",
    modify: "Edit my expenditure",
    expenseIntro:
      "Enter annual external expenditure excluding tax, in euros, for the same year. Enter each expense in one category only. Exclude salaries, taxes and internal expenditure. Enter 0 only when expenditure is genuinely zero; do not replace an unknown amount with zero.",
    categories: [
      "IT & digital services",
      "Professional services",
      "Goods & purchases",
      "Logistics & transport",
      "Business travel",
      "Accommodation & events",
      "Other external expenditure",
    ],
    hints: [
      "Software, cloud, SaaS, managed IT",
      "Consultancy, accounting, legal services",
      "Office supplies, equipment, materials",
      "Freight, delivery, transport providers",
      "Flights, trains, taxis, car rental",
      "Hotels, conferences, business events",
      "Marketing, subscriptions, other external costs",
    ],
    placeholder: "e.g. 1250.50 or 0",
    result: "Indicative annual emissions estimate",
    indicative:
      "Deterministic expenditure-based estimate · Indicative · Not audited",
    summary: "Review before payment",
    summaryIntro:
      "Check your company, reference year, result and document language.",
    document: "Document",
    documentValue: "Indicative CO₂e attestation PDF",
    price: "Price",
    delivery: "Delivery",
    afterPayment: "After payment confirmation",
    afterCredit: "After using one credit",
    credit: "1 pack credit",
    unitPrice: "89 € · VAT not applicable under the issuer’s tax regime",
    keyTitle: "I already have an access key or a pack",
    key: "Access key",
    checkKey: "Check my key",
    checking: "Checking…",
    remaining: "Remaining credits",
    payInstead: "Pay 89 € instead",
    processing: "Processing…",
    generate: "Generate my attestation — 89 €",
    generateCredit: "Generate my attestation (1 credit)",
    accepted:
      "I understand that this attestation is indicative, not audited, not regulatory, not a CSRD/ESRS report, and depends on the information I provide.",
    archive:
      "Download and save your PDF immediately after generation. Certif-Scope does not retain a recoverable copy. Reissue is not automatically included.",
    keyNotice:
      "Using an access key consumes one credit per attestation. Credits are non-refundable and non-transferable.",
    question: "Unsure whether the document is suitable?",
    contact: "Contact us before payment",
    sample: "View the sample PDF",
    errors: {
      company: "Enter your company name.",
      sector: "Select your activity sector.",
      year: "Choose a year between 2000 and",
      expenses:
        "Complete all seven categories with non-negative amounts and up to two decimals. At least one amount must be greater than zero.",
      accepted:
        "Confirm that you understand the indicative scope before continuing.",
      key: "Invalid, expired or exhausted access key.",
      keyNetwork: "Unable to check the key. Please try again.",
      submit:
        "Unable to process your request. Please try again or contact support.",
    },
  },
  de: {
    title: "Indikative CO₂e-Bescheinigung für Ihr Unternehmen erstellen",
    intro:
      "Erstellen Sie ein standardisiertes PDF aus sieben Kategorien jährlicher externer Ausgaben. Bestätigen Sie vor der Bestellung, dass Ihr Empfänger diese indikative Methode akzeptiert.",
    steps: ["Unternehmen", "Ausgaben", "Kontrolle"],
    stepTitles: [
      "Unternehmen und Kontext",
      "Jährliche Ausgaben",
      "Kontrolle vor der Zahlung",
    ],
    step: "Schritt",
    of: "von",
    company: "Name des Unternehmens / der juristischen Einheit",
    sector: "Haupttätigkeitsbereich",
    selectSector: "Tätigkeitsbereich auswählen",
    identifier: "Unternehmenskennung (optional)",
    year: "Bezugsjahr",
    country: "Hauptland",
    language: "Sprache der Bescheinigung",
    countries: ["Frankreich", "Deutschland", "Andere EU"],
    next: "Weiter zu den Ausgaben",
    back: "Zurück",
    review: "Schätzung kontrollieren",
    modify: "Ausgaben bearbeiten",
    expenseIntro:
      "Geben Sie die jährlichen externen Ausgaben ohne Steuern in Euro für dasselbe Jahr ein. Erfassen Sie jede Ausgabe nur in einer Kategorie. Löhne, Steuern und interne Ausgaben sind ausgeschlossen. Geben Sie 0 nur für tatsächlich nicht vorhandene Ausgaben ein; ersetzen Sie unbekannte Beträge nicht durch null.",
    categories: [
      "IT- und Digitalleistungen",
      "Professionelle Dienstleistungen",
      "Waren und Beschaffung",
      "Logistik und Transport",
      "Geschäftsreisen",
      "Übernachtungen und Veranstaltungen",
      "Sonstige externe Ausgaben",
    ],
    hints: [
      "Software, Cloud, SaaS, IT-Betreuung",
      "Beratung, Buchhaltung, juristische Dienstleistungen",
      "Büromaterial, Ausstattung, Materialien",
      "Fracht, Lieferung, externe Transportdienstleister",
      "Flüge, Bahnreisen, Taxis, Mietwagen",
      "Hotels, Konferenzen, Unternehmensveranstaltungen",
      "Marketing, Abonnements, sonstige externe Kosten",
    ],
    placeholder: "z. B. 1250,50 oder 0",
    result: "Indikative Schätzung der jährlichen Emissionen",
    indicative:
      "Deterministische ausgabenbasierte Schätzung · Indikativ · Nicht auditiert",
    summary: "Zusammenfassung vor Zahlung",
    summaryIntro:
      "Prüfen Sie Unternehmen, Bezugsjahr, Ergebnis und Sprache des Dokuments.",
    document: "Dokument",
    documentValue: "Indikative CO₂e-Bescheinigung als PDF",
    price: "Preis",
    delivery: "Bereitstellung",
    afterPayment: "Nach Zahlungsbestätigung",
    afterCredit: "Nach Verwendung eines Guthabens",
    credit: "1 Paketguthaben",
    unitPrice: "89 € · Keine Umsatzsteuer gemäß Steuerregelung des Ausstellers",
    keyTitle: "Ich habe bereits einen Zugangsschlüssel oder ein Paket",
    key: "Zugangsschlüssel",
    checkKey: "Schlüssel prüfen",
    checking: "Prüfung…",
    remaining: "Verbleibendes Guthaben",
    payInstead: "Stattdessen 89 € bezahlen",
    processing: "Verarbeitung…",
    generate: "Bescheinigung erstellen — 89 €",
    generateCredit: "Bescheinigung erstellen (1 Guthaben)",
    accepted:
      "Ich verstehe, dass diese Bescheinigung indikativ, nicht auditiert, nicht regulatorisch und kein CSRD-/ESRS-Bericht ist und von meinen Angaben abhängt.",
    archive:
      "Laden Sie das PDF unmittelbar nach der Erstellung herunter und speichern Sie es. Certif-Scope bewahrt keine wiederherstellbare Kopie auf. Eine Neuausstellung ist nicht automatisch enthalten.",
    keyNotice:
      "Ein Zugangsschlüssel verbraucht ein Guthaben pro Bescheinigung. Guthaben sind nicht erstattungsfähig und nicht übertragbar.",
    question: "Unsicher, ob das Dokument geeignet ist?",
    contact: "Kontaktieren Sie uns vor der Zahlung",
    sample: "Beispiel-PDF ansehen",
    errors: {
      company: "Geben Sie den Unternehmensnamen ein.",
      sector: "Wählen Sie einen Tätigkeitsbereich aus.",
      year: "Wählen Sie ein Jahr zwischen 2000 und",
      expenses:
        "Füllen Sie alle sieben Kategorien mit nicht negativen Beträgen und höchstens zwei Dezimalstellen aus. Mindestens ein Betrag muss größer als null sein.",
      accepted: "Bestätigen Sie den indikativen Umfang, bevor Sie fortfahren.",
      key: "Ungültiger, abgelaufener oder verbrauchter Zugangsschlüssel.",
      keyNetwork:
        "Der Schlüssel konnte nicht geprüft werden. Versuchen Sie es erneut.",
      submit:
        "Ihre Anfrage konnte nicht verarbeitet werden. Versuchen Sie es erneut oder kontaktieren Sie den Support.",
    },
  },
} as const;
