import type { EuNonCoreLocale } from "./eu-flow";

// Extra homepage labels, shared with the French template. Longer methodological
// descriptions come from the already translated document and form dictionaries.
export type HomeUI = {
  labels: string[];
  suitable: string[];
  exclusions: string[];
  questions: string[];
  packs: string;
  correction: string;
  download: string;
  reuse: string;
  support: string;
};
export const HOME_UI: Record<EuNonCoreLocale, HomeUI> = {
  es: {
    labels: [
      "Decisión rápida",
      "Confirmar con el destinatario",
      "No adecuado",
      "Aclaración importante",
      "Un documento listo para enviar.",
      "Consultar la metodología completa",
      "89 € por su certificado CO₂e indicativo",
      "Por documento · sin suscripción",
      "Qué incluyen los 89 €",
      "¿Necesita varios documentos?",
      "Sus preguntas antes de comprar",
      "Datos, contenido del documento, packs y asistencia para preparar su pedido.",
      "¿Dudas antes de pagar?",
      "Contacto",
      "Comprender el cálculo",
      "Ver el precio",
      "Leer la guía para pymes →",
      "Recordatorio del alcance",
      "Privacidad →",
      "Volver arriba",
      "Inicio",
      "Generar",
      "Precio fijo 89 €",
      "Sin suscripción",
      "PDF estandarizado",
      "ID verificable",
      "No es auditoría / no es CSRD",
      "Antes y después de su pedido",
    ],
    suitable: [
      "Un cliente solicita información básica de carbono",
      "Una plataforma de proveedores solicita un documento CO₂e",
      "Un banco solicita información de carbono o ESG",
      "Una aseguradora solicita información ambiental",
      "Una licitación no impone una metodología",
    ],
    exclusions: [
      "Se exige una auditoría de carbono completa",
      "Se impone una norma o metodología específica",
      "Se exigen alcances 1, 2 y 3 detallados",
      "La verificación externa es obligatoria",
      "Se exige un informe CSRD / ESRS",
    ],
    questions: [
      "¿Es adecuado para mi solicitud?",
      "¿Qué datos debo preparar?",
      "¿Qué recibo por 89 €?",
      "¿Qué método y coeficientes se utilizan?",
      "¿Puedo enviar el mismo PDF a varios destinatarios?",
      "¿Cómo funcionan los packs?",
      "¿Puedo corregir un documento emitido?",
      "¿Qué hago si falla la descarga o pierdo el PDF?",
      "¿Qué confirma la verificación documental?",
    ],
    packs:
      "Tras confirmar el pago, las claves se envían por email. Cada clave genera un documento y debe usarse en 365 días desde su creación. Introduzca y compruebe la clave en el formulario. Si no llega el email, revise el correo no deseado y contacte con soporte sin comprar de nuevo.",
    correction:
      "Revise los datos antes de pagar. Tras la emisión, contacte con soporte con la referencia del pedido y la corrección solicitada. La reemisión no es automáticamente gratuita; las condiciones se confirman antes de un nuevo pedido.",
    download:
      "Reintente desde la página de retorno y contacte con soporte sin volver a comprar. Revise también el email de entrega y el correo no deseado. Archive el PDF al recibirlo: Certif-Scope no conserva una copia recuperable. Consulte con soporte si lo pierde.",
    reuse:
      "Pago único por documento, sin suscripción. IVA no aplicable según el régimen del emisor indicado en el aviso legal. Puede enviar el mismo PDF a varios destinatarios para la misma empresa, año y datos, si aceptan su alcance.",
    support:
      "Contacte con soporte por problemas de descarga, preguntas sobre el pedido o correcciones. La reemisión no está incluida automáticamente; sus condiciones se confirman tras revisar la solicitud. El precio no incluye auditoría, validación externa de emisiones ni garantía de aceptación.",
  },
  it: {
    labels: [
      "Decisione rapida",
      "Confermare con il destinatario",
      "Non adatto",
      "Chiarimento importante",
      "Un documento pronto da inviare.",
      "Consultare la metodologia completa",
      "89 € per la vostra attestazione CO₂e indicativa",
      "Per documento · senza abbonamento",
      "Cosa comprendono gli 89 €",
      "Servono più documenti?",
      "Le vostre domande prima dell’ordine",
      "Dati, contenuto del documento, pacchetti e assistenza per preparare l’ordine.",
      "Dubbi prima di pagare?",
      "Contatti",
      "Comprendere il calcolo",
      "Vedere il prezzo",
      "Leggere la guida per PMI →",
      "Riepilogo del perimetro",
      "Privacy →",
      "Torna in alto",
      "Home",
      "Genera",
      "Prezzo fisso 89 €",
      "Senza abbonamento",
      "PDF standardizzato",
      "ID verificabile",
      "Non è un audit / non è CSRD",
      "Prima e dopo l’ordine",
    ],
    suitable: [
      "Un cliente richiede informazioni semplici sul carbonio",
      "Una piattaforma fornitori richiede un documento CO₂e",
      "Una banca richiede informazioni sul carbonio o ESG",
      "Un’assicurazione richiede informazioni ambientali",
      "Una gara non impone una metodologia",
    ],
    exclusions: [
      "È richiesto un audit completo del carbonio",
      "È imposto uno standard o un metodo specifico",
      "Sono richiesti Scope 1, 2 e 3 dettagliati",
      "La verifica esterna è obbligatoria",
      "È richiesta una rendicontazione CSRD / ESRS",
    ],
    questions: [
      "È adatto alla mia richiesta?",
      "Quali dati devo preparare?",
      "Cosa ricevo per 89 €?",
      "Quale metodo e quali coefficienti vengono utilizzati?",
      "Posso inviare lo stesso PDF a più destinatari?",
      "Come funzionano i pacchetti?",
      "Posso correggere un documento emesso?",
      "Cosa fare se il download non riesce o perdo il PDF?",
      "Cosa conferma la verifica documentale?",
    ],
    packs:
      "Dopo la conferma del pagamento, le chiavi vengono inviate via email. Ogni chiave genera un documento e va usata entro 365 giorni dalla creazione. Inserite e verificate la chiave nel modulo. Se l’email non arriva, controllate lo spam e contattate l’assistenza senza riacquistare.",
    correction:
      "Controllate i dati prima di pagare. Dopo l’emissione, contattate l’assistenza con il riferimento dell’ordine e la correzione richiesta. La riemissione non è automaticamente gratuita; le condizioni vengono confermate prima di un nuovo ordine.",
    download:
      "Riprovate dalla pagina di ritorno e contattate l’assistenza senza riacquistare. Controllate anche l’email di consegna e lo spam. Archiviate il PDF appena ricevuto: Certif-Scope non conserva una copia recuperabile. In caso di perdita, contattate l’assistenza.",
    reuse:
      "Pagamento unico per documento, senza abbonamento. IVA non applicabile secondo il regime dell’emittente indicato nelle note legali. Lo stesso PDF può essere inviato a più destinatari per la stessa azienda, anno e dati, se ne accettano il perimetro.",
    support:
      "Contattate l’assistenza per problemi di download, domande sull’ordine o correzioni. La riemissione non è automaticamente inclusa; le condizioni vengono confermate dopo l’esame della richiesta. Il prezzo non include audit, validazione esterna delle emissioni o garanzia di accettazione.",
  },
  pl: {
    labels: [
      "Szybka decyzja",
      "Potwierdź z odbiorcą",
      "Nieodpowiednie",
      "Ważne wyjaśnienie",
      "Dokument gotowy do wysłania.",
      "Zobacz pełną metodologię",
      "89 € za orientacyjne zaświadczenie CO₂e",
      "Za dokument · bez abonamentu",
      "Co obejmuje cena 89 €",
      "Potrzebujesz kilku dokumentów?",
      "Pytania przed zamówieniem",
      "Dane, zawartość dokumentu, pakiety i pomoc przed zamówieniem.",
      "Wątpliwości przed płatnością?",
      "Kontakt",
      "Jak działa obliczenie",
      "Zobacz cenę",
      "Przeczytaj poradnik dla MŚP →",
      "Przypomnienie zakresu",
      "Prywatność →",
      "Na górę",
      "Strona główna",
      "Generuj",
      "Stała cena 89 €",
      "Bez abonamentu",
      "Standardowy PDF",
      "Weryfikowalny ID",
      "Nie audyt / nie CSRD",
      "Przed i po zamówieniu",
    ],
    suitable: [
      "Klient prosi o podstawową informację o emisjach",
      "Platforma dostawców wymaga dokumentu CO₂e",
      "Bank prosi o informacje o emisjach lub ESG",
      "Ubezpieczyciel prosi o informacje środowiskowe",
      "Przetarg nie narzuca metody",
    ],
    exclusions: [
      "Wymagany jest pełny audyt emisji",
      "Wymagany jest określony standard lub metoda",
      "Wymagane są szczegółowe zakresy 1, 2 i 3",
      "Obowiązkowa jest zewnętrzna weryfikacja",
      "Wymagane jest raportowanie CSRD / ESRS",
    ],
    questions: [
      "Czy to odpowiada mojej potrzebie?",
      "Jakie dane przygotować?",
      "Co otrzymam za 89 €?",
      "Jaka metoda i współczynniki są stosowane?",
      "Czy mogę wysłać ten sam PDF kilku odbiorcom?",
      "Jak działają pakiety?",
      "Czy można poprawić wydany dokument?",
      "Co zrobić, gdy pobieranie nie działa lub zgubię PDF?",
      "Co potwierdza weryfikacja dokumentu?",
    ],
    packs:
      "Po potwierdzeniu płatności klucze są wysyłane emailem. Każdy klucz tworzy jeden dokument i należy go użyć w ciągu 365 dni od utworzenia. Wprowadź i sprawdź klucz w formularzu. Jeśli email nie dotrze, sprawdź spam i skontaktuj się z pomocą bez ponownego zakupu.",
    correction:
      "Sprawdź dane przed płatnością. Po wydaniu dokumentu skontaktuj się z pomocą, podając numer zamówienia i żądaną poprawkę. Ponowne wydanie nie jest automatycznie bezpłatne; warunki zostaną potwierdzone przed nowym zamówieniem.",
    download:
      "Spróbuj ponownie na stronie powrotu i skontaktuj się z pomocą bez ponownego zakupu. Sprawdź email z dostawą i spam. Zapisz PDF od razu: Certif-Scope nie przechowuje kopii możliwej do odzyskania. W razie utraty skontaktuj się z pomocą.",
    reuse:
      "Jednorazowa opłata za dokument, bez abonamentu. VAT nie ma zastosowania zgodnie z zasadami wystawcy podanymi w informacjach prawnych. Ten sam PDF można wysłać kilku odbiorcom dla tej samej firmy, roku i danych, jeśli akceptują zakres.",
    support:
      "Skontaktuj się z pomocą w sprawie pobierania, zamówienia lub poprawek. Ponowne wydanie nie jest automatycznie wliczone; warunki potwierdzamy po rozpatrzeniu prośby. Cena nie obejmuje audytu, zewnętrznej walidacji emisji ani gwarancji akceptacji.",
  },
  nl: {
    labels: [
      "Snelle beslissing",
      "Bevestig dit met de ontvanger",
      "Niet geschikt",
      "Belangrijke toelichting",
      "Een document dat klaar is om te versturen.",
      "Bekijk de volledige methodologie",
      "89 € voor uw indicatieve CO₂e-attest",
      "Per document · geen abonnement",
      "Wat de 89 € omvat",
      "Meerdere documenten nodig?",
      "Uw vragen vóór het bestellen",
      "Gegevens, documentinhoud, pakketten en ondersteuning voor uw bestelling.",
      "Twijfels vóór betaling?",
      "Contact",
      "De berekening begrijpen",
      "Bekijk de prijs",
      "Lees de mkb-gids →",
      "Overzicht van de reikwijdte",
      "Privacy →",
      "Naar boven",
      "Home",
      "Genereren",
      "Vaste prijs 89 €",
      "Geen abonnement",
      "Gestandaardiseerde PDF",
      "Verifieerbare ID",
      "Geen audit / geen CSRD",
      "Vóór en na uw bestelling",
    ],
    suitable: [
      "Een klant vraagt eenvoudige koolstofinformatie",
      "Een leveranciersplatform vraagt een CO₂e-document",
      "Een bank vraagt koolstof- of ESG-informatie",
      "Een verzekeraar vraagt milieu-informatie",
      "Een aanbesteding schrijft geen methode voor",
    ],
    exclusions: [
      "Een volledige koolstofaudit is vereist",
      "Een specifieke norm of methode is verplicht",
      "Gedetailleerde Scopes 1, 2 en 3 zijn vereist",
      "Externe verificatie is verplicht",
      "CSRD / ESRS-rapportage is vereist",
    ],
    questions: [
      "Past dit bij mijn verzoek?",
      "Welke gegevens moet ik voorbereiden?",
      "Wat ontvang ik voor 89 €?",
      "Welke methode en coëfficiënten worden gebruikt?",
      "Kan ik dezelfde PDF naar meerdere ontvangers sturen?",
      "Hoe werken pakketten?",
      "Kan ik een uitgegeven document corrigeren?",
      "Wat als downloaden mislukt of ik de PDF verlies?",
      "Wat bevestigt documentaire verificatie?",
    ],
    packs:
      "Na bevestiging van betaling worden de sleutels per email verstuurd. Elke sleutel maakt één document en moet binnen 365 dagen na aanmaak worden gebruikt. Voer de sleutel in het formulier in en controleer deze. Controleer spam en neem contact op met ondersteuning als de email ontbreekt, zonder opnieuw te kopen.",
    correction:
      "Controleer gegevens vóór betaling. Neem na uitgifte contact op met ondersteuning met uw bestelreferentie en gewenste correctie. Heruitgifte is niet automatisch gratis; voorwaarden worden vóór een nieuwe bestelling bevestigd.",
    download:
      "Probeer opnieuw vanaf de terugkeerpagina en neem contact op met ondersteuning zonder opnieuw te bestellen. Controleer de bezorgemail en spam. Bewaar uw PDF meteen: Certif-Scope bewaart geen terughaalbare kopie. Neem bij verlies contact op met ondersteuning.",
    reuse:
      "Eenmalige betaling per document, geen abonnement. Btw is niet van toepassing volgens het regime van de uitgever in de juridische informatie. Dezelfde PDF kan voor hetzelfde bedrijf, jaar en gegevens naar meerdere ontvangers worden gestuurd als zij de reikwijdte accepteren.",
    support:
      "Neem contact op met ondersteuning bij downloadproblemen, bestelvragen of correcties. Heruitgifte is niet automatisch inbegrepen; voorwaarden volgen na beoordeling. De prijs omvat geen audit, externe validatie van emissies of acceptatiegarantie.",
  },
  pt: {
    labels: [
      "Decisão rápida",
      "Confirmar com o destinatário",
      "Não adequado",
      "Esclarecimento importante",
      "Um documento pronto a enviar.",
      "Consultar a metodologia completa",
      "89 € pelo seu certificado CO₂e indicativo",
      "Por documento · sem subscrição",
      "O que incluem os 89 €",
      "Precisa de vários documentos?",
      "As suas perguntas antes de encomendar",
      "Dados, conteúdo do documento, packs e apoio para preparar a encomenda.",
      "Dúvidas antes de pagar?",
      "Contacto",
      "Compreender o cálculo",
      "Ver o preço",
      "Ler o guia para PME →",
      "Resumo do âmbito",
      "Privacidade →",
      "Voltar ao topo",
      "Início",
      "Gerar",
      "Preço fixo 89 €",
      "Sem subscrição",
      "PDF normalizado",
      "ID verificável",
      "Não é auditoria / não é CSRD",
      "Antes e depois da encomenda",
    ],
    suitable: [
      "Um cliente pede informação simples sobre carbono",
      "Uma plataforma de fornecedores pede um documento CO₂e",
      "Um banco pede informação sobre carbono ou ESG",
      "Uma seguradora pede informação ambiental",
      "Um concurso não impõe uma metodologia",
    ],
    exclusions: [
      "É exigida uma auditoria de carbono completa",
      "É imposta uma norma ou metodologia específica",
      "São exigidos âmbitos 1, 2 e 3 detalhados",
      "A verificação externa é obrigatória",
      "É exigido um relatório CSRD / ESRS",
    ],
    questions: [
      "É adequado ao meu pedido?",
      "Que dados devo preparar?",
      "O que recebo por 89 €?",
      "Que método e coeficientes são utilizados?",
      "Posso enviar o mesmo PDF a vários destinatários?",
      "Como funcionam os packs?",
      "Posso corrigir um documento emitido?",
      "O que fazer se a descarga falhar ou perder o PDF?",
      "O que confirma a verificação documental?",
    ],
    packs:
      "Após confirmação do pagamento, as chaves são enviadas por email. Cada chave gera um documento e deve ser utilizada em 365 dias após a criação. Introduza e verifique a chave no formulário. Se o email não chegar, veja o spam e contacte o apoio sem comprar novamente.",
    correction:
      "Verifique os dados antes de pagar. Após emissão, contacte o apoio com a referência da encomenda e a correção pretendida. A reemissão não é automaticamente gratuita; as condições são confirmadas antes de uma nova encomenda.",
    download:
      "Tente novamente na página de regresso e contacte o apoio sem voltar a comprar. Veja o email de entrega e o spam. Arquive o PDF ao recebê-lo: a Certif-Scope não conserva uma cópia recuperável. Em caso de perda, contacte o apoio.",
    reuse:
      "Pagamento único por documento, sem subscrição. IVA não aplicável segundo o regime do emitente indicado na informação legal. O mesmo PDF pode ser enviado a vários destinatários para a mesma empresa, ano e dados, se aceitarem o âmbito.",
    support:
      "Contacte o apoio por problemas de descarga, questões sobre a encomenda ou correções. A reemissão não está automaticamente incluída; as condições são confirmadas após análise. O preço não inclui auditoria, validação externa das emissões ou garantia de aceitação.",
  },
  ro: {
    labels: [
      "Decizie rapidă",
      "Confirmați cu destinatarul",
      "Neadecvat",
      "Clarificare importantă",
      "Un document gata de trimis.",
      "Consultați metodologia completă",
      "89 € pentru atestatul CO₂e indicativ",
      "Per document · fără abonament",
      "Ce includ cei 89 €",
      "Aveți nevoie de mai multe documente?",
      "Întrebări înainte de comandă",
      "Date, conținutul documentului, pachete și asistență pentru comandă.",
      "Nelămuriri înainte de plată?",
      "Contact",
      "Înțelegerea calculului",
      "Vedeți prețul",
      "Citiți ghidul pentru IMM-uri →",
      "Reamintirea domeniului",
      "Confidențialitate →",
      "Sus",
      "Acasă",
      "Generează",
      "Preț fix 89 €",
      "Fără abonament",
      "PDF standardizat",
      "ID verificabil",
      "Nu este audit / nu este CSRD",
      "Înainte și după comandă",
    ],
    suitable: [
      "Un client solicită informații simple despre carbon",
      "O platformă de furnizori solicită un document CO₂e",
      "O bancă solicită informații despre carbon sau ESG",
      "Un asigurător solicită informații de mediu",
      "O licitație nu impune o metodă",
    ],
    exclusions: [
      "Este necesar un audit complet al emisiilor",
      "Este impus un standard sau o metodă specifică",
      "Sunt necesare domeniile 1, 2 și 3 detaliate",
      "Verificarea externă este obligatorie",
      "Este necesară raportarea CSRD / ESRS",
    ],
    questions: [
      "Este potrivit pentru cererea mea?",
      "Ce date trebuie să pregătesc?",
      "Ce primesc pentru 89 €?",
      "Ce metodă și coeficienți sunt utilizați?",
      "Pot trimite același PDF mai multor destinatari?",
      "Cum funcționează pachetele?",
      "Pot corecta un document emis?",
      "Ce fac dacă descărcarea eșuează sau pierd PDF-ul?",
      "Ce confirmă verificarea documentară?",
    ],
    packs:
      "După confirmarea plății, cheile sunt trimise prin email. Fiecare cheie creează un document și trebuie folosită în 365 de zile de la creare. Introduceți și verificați cheia în formular. Dacă emailul lipsește, verificați spamul și contactați asistența fără a cumpăra din nou.",
    correction:
      "Verificați datele înainte de plată. După emitere, contactați asistența cu referința comenzii și corectarea dorită. Reemiterea nu este automat gratuită; condițiile se confirmă înainte de o comandă nouă.",
    download:
      "Încercați din nou de pe pagina de revenire și contactați asistența fără a cumpăra din nou. Verificați emailul de livrare și spamul. Salvați PDF-ul imediat: Certif-Scope nu păstrează o copie recuperabilă. Dacă îl pierdeți, contactați asistența.",
    reuse:
      "Plată unică per document, fără abonament. TVA nu se aplică potrivit regimului emitentului din informațiile legale. Același PDF poate fi trimis mai multor destinatari pentru aceeași companie, an și date, dacă acceptă domeniul.",
    support:
      "Contactați asistența pentru probleme de descărcare, întrebări despre comandă sau corectări. Reemiterea nu este inclusă automat; condițiile se confirmă după analiză. Prețul nu include audit, validarea externă a emisiilor sau garanția acceptării.",
  },
  sv: {
    labels: [
      "Snabbt beslut",
      "Bekräfta med mottagaren",
      "Inte lämpligt",
      "Viktigt förtydligande",
      "Ett dokument redo att skickas.",
      "Se hela metodiken",
      "89 € för ditt indikativa CO₂e-intyg",
      "Per dokument · inget abonnemang",
      "Vad de 89 € omfattar",
      "Behöver du flera dokument?",
      "Dina frågor före beställningen",
      "Uppgifter, dokumentinnehåll, paket och support inför beställningen.",
      "Osäker före betalning?",
      "Kontakt",
      "Förstå beräkningen",
      "Se priset",
      "Läs guiden för småföretag →",
      "Påminnelse om omfattningen",
      "Integritet →",
      "Till toppen",
      "Hem",
      "Skapa",
      "Fast pris 89 €",
      "Inget abonnemang",
      "Standardiserad PDF",
      "Verifierbart ID",
      "Ingen revision / ingen CSRD",
      "Före och efter beställningen",
    ],
    suitable: [
      "En kund begär enkel koldioxidinformation",
      "En leverantörsplattform begär ett CO₂e-dokument",
      "En bank begär koldioxid- eller ESG-information",
      "Ett försäkringsbolag begär miljöinformation",
      "En upphandling föreskriver ingen metod",
    ],
    exclusions: [
      "En fullständig koldioxidrevision krävs",
      "En särskild standard eller metod är obligatorisk",
      "Detaljerade Scope 1, 2 och 3 krävs",
      "Extern verifiering är obligatorisk",
      "CSRD / ESRS-rapportering krävs",
    ],
    questions: [
      "Passar det min förfrågan?",
      "Vilka uppgifter ska jag förbereda?",
      "Vad får jag för 89 €?",
      "Vilken metod och vilka koefficienter används?",
      "Kan jag skicka samma PDF till flera mottagare?",
      "Hur fungerar paketen?",
      "Kan jag rätta ett utfärdat dokument?",
      "Vad gör jag om hämtningen misslyckas eller PDF-filen försvinner?",
      "Vad bekräftar dokumentverifieringen?",
    ],
    packs:
      "Efter bekräftad betalning skickas nycklarna via email. Varje nyckel skapar ett dokument och ska användas inom 365 dagar från skapandet. Ange och kontrollera nyckeln i formuläret. Kontrollera skräppost och kontakta support om emailet saknas, utan att köpa igen.",
    correction:
      "Kontrollera uppgifterna före betalning. Kontakta support efter utfärdandet med beställningsreferens och önskad rättelse. Ny utfärdande är inte automatiskt gratis; villkoren bekräftas före en ny beställning.",
    download:
      "Försök igen från retursidan och kontakta support utan att köpa igen. Kontrollera leveransemail och skräppost. Spara PDF-filen direkt: Certif-Scope behåller ingen återställbar kopia. Kontakta support vid förlust.",
    reuse:
      "Engångsbetalning per dokument, inget abonnemang. Moms tillämpas inte enligt utfärdarens skatteregim i den juridiska informationen. Samma PDF kan skickas till flera mottagare för samma företag, år och uppgifter om de godtar omfattningen.",
    support:
      "Kontakta support vid hämtningsproblem, beställningsfrågor eller rättelser. Ny utfärdande ingår inte automatiskt; villkoren bekräftas efter granskning. Priset omfattar inte revision, extern validering av utsläpp eller garanti för godkännande.",
  },
  da: {
    labels: [
      "Hurtig beslutning",
      "Bekræft med modtageren",
      "Ikke egnet",
      "Vigtig præcisering",
      "Et dokument klar til at sende.",
      "Se den fulde metode",
      "89 € for din vejledende CO₂e-attest",
      "Pr. dokument · intet abonnement",
      "Hvad de 89 € omfatter",
      "Brug for flere dokumenter?",
      "Dine spørgsmål før bestilling",
      "Data, dokumentindhold, pakker og support før bestilling.",
      "I tvivl før betaling?",
      "Kontakt",
      "Forstå beregningen",
      "Se prisen",
      "Læs guiden til SMV’er →",
      "Påmindelse om omfanget",
      "Privatliv →",
      "Til toppen",
      "Hjem",
      "Generér",
      "Fast pris 89 €",
      "Intet abonnement",
      "Standardiseret PDF",
      "Verificerbart ID",
      "Ikke revision / ikke CSRD",
      "Før og efter bestilling",
    ],
    suitable: [
      "En kunde beder om enkel kulstofinformation",
      "En leverandørplatform beder om et CO₂e-dokument",
      "En bank beder om kulstof- eller ESG-information",
      "Et forsikringsselskab beder om miljøinformation",
      "Et udbud foreskriver ingen metode",
    ],
    exclusions: [
      "En fuld kulstofrevision kræves",
      "En bestemt standard eller metode er obligatorisk",
      "Detaljerede Scope 1, 2 og 3 kræves",
      "Ekstern verifikation er obligatorisk",
      "CSRD / ESRS-rapportering kræves",
    ],
    questions: [
      "Passer det til min forespørgsel?",
      "Hvilke data skal jeg forberede?",
      "Hvad får jeg for 89 €?",
      "Hvilken metode og hvilke koefficienter bruges?",
      "Kan jeg sende samme PDF til flere modtagere?",
      "Hvordan fungerer pakkerne?",
      "Kan jeg rette et udstedt dokument?",
      "Hvad hvis download fejler, eller jeg mister PDF’en?",
      "Hvad bekræfter dokumentverifikation?",
    ],
    packs:
      "Efter bekræftet betaling sendes nøglerne via email. Hver nøgle opretter ét dokument og skal bruges inden for 365 dage efter oprettelsen. Indtast og kontrollér nøglen i formularen. Tjek spam og kontakt support, hvis emailen mangler, uden at købe igen.",
    correction:
      "Kontrollér data før betaling. Kontakt support efter udstedelsen med ordrereference og ønsket rettelse. Genudstedelse er ikke automatisk gratis; vilkårene bekræftes før en ny ordre.",
    download:
      "Prøv igen fra retursiden, og kontakt support uden at købe igen. Tjek leveringsemail og spam. Gem PDF’en straks: Certif-Scope gemmer ingen gendannelig kopi. Kontakt support, hvis dokumentet mistes.",
    reuse:
      "Engangsbetaling pr. dokument, intet abonnement. Moms gælder ikke efter udstederens skatteordning i de juridiske oplysninger. Samme PDF kan sendes til flere modtagere for samme virksomhed, år og data, hvis de accepterer omfanget.",
    support:
      "Kontakt support ved downloadproblemer, ordrespørgsmål eller rettelser. Genudstedelse er ikke automatisk inkluderet; vilkår bekræftes efter gennemgang. Prisen inkluderer ikke revision, ekstern validering af emissioner eller acceptgaranti.",
  },
  fi: {
    labels: [
      "Nopea päätös",
      "Vahvista vastaanottajalta",
      "Ei sovellu",
      "Tärkeä selvennys",
      "Asiakirja valmiina lähetettäväksi.",
      "Tutustu koko menetelmään",
      "89 € suuntaa-antavasta CO₂e-todistuksesta",
      "Asiakirjaa kohti · ei tilausta",
      "Mitä 89 € sisältää",
      "Tarvitsetko useita asiakirjoja?",
      "Kysymyksesi ennen tilaamista",
      "Tiedot, asiakirjan sisältö, paketit ja tuki ennen tilausta.",
      "Epävarma ennen maksamista?",
      "Yhteystiedot",
      "Laskennan ymmärtäminen",
      "Katso hinta",
      "Lue pk-yrityksen opas →",
      "Laajuuden muistutus",
      "Tietosuoja →",
      "Takaisin ylös",
      "Etusivu",
      "Luo",
      "Kiinteä hinta 89 €",
      "Ei tilausta",
      "Vakioitu PDF",
      "Tarkistettava tunniste",
      "Ei auditointi / ei CSRD",
      "Ennen tilausta ja sen jälkeen",
    ],
    suitable: [
      "Asiakas pyytää yksinkertaisia hiilitietoja",
      "Toimittaja-alusta pyytää CO₂e-asiakirjaa",
      "Pankki pyytää hiili- tai ESG-tietoja",
      "Vakuutusyhtiö pyytää ympäristötietoja",
      "Tarjouskilpailussa ei määrätä menetelmää",
    ],
    exclusions: [
      "Vaaditaan täydellinen hiiliauditointi",
      "Tietty standardi tai menetelmä on pakollinen",
      "Vaaditaan yksityiskohtaiset Scope 1, 2 ja 3",
      "Ulkoinen todentaminen on pakollinen",
      "Vaaditaan CSRD / ESRS-raportointi",
    ],
    questions: [
      "Sopiiko tämä pyyntööni?",
      "Mitä tietoja valmistelen?",
      "Mitä saan 89 eurolla?",
      "Mitä menetelmää ja kertoimia käytetään?",
      "Voinko lähettää saman PDF:n usealle vastaanottajalle?",
      "Miten paketit toimivat?",
      "Voinko korjata annetun asiakirjan?",
      "Mitä teen, jos lataus epäonnistuu tai kadotan PDF:n?",
      "Mitä asiakirjan tarkistus vahvistaa?",
    ],
    packs:
      "Maksun vahvistamisen jälkeen avaimet lähetetään sähköpostitse. Yksi avain luo yhden asiakirjan ja on käytettävä 365 päivän kuluessa luomisesta. Syötä ja tarkista avain lomakkeella. Tarkista roskaposti ja ota yhteyttä tukeen, jos viesti puuttuu, ostamatta uudelleen.",
    correction:
      "Tarkista tiedot ennen maksua. Ota antamisen jälkeen yhteyttä tukeen tilausviitteellä ja halutulla korjauksella. Uudelleenanto ei ole automaattisesti maksuton; ehdot vahvistetaan ennen uutta tilausta.",
    download:
      "Yritä uudelleen paluusivulla ja ota yhteyttä tukeen ostamatta uudelleen. Tarkista toimitussähköposti ja roskaposti. Tallenna PDF heti: Certif-Scope ei säilytä palautettavaa kopiota. Ota kadotessa yhteyttä tukeen.",
    reuse:
      "Kertamaksu asiakirjaa kohti, ei tilausta. Arvonlisäveroa ei sovelleta antajan oikeudellisissa tiedoissa mainitun verojärjestelmän mukaan. Saman PDF:n voi lähettää useille vastaanottajille samasta yrityksestä, vuodesta ja tiedoista, jos he hyväksyvät laajuuden.",
    support:
      "Ota yhteyttä tukeen latausongelmissa, tilausta koskevissa kysymyksissä tai korjauksissa. Uudelleenanto ei sisälly automaattisesti; ehdot vahvistetaan tarkastelun jälkeen. Hintaan ei sisälly auditointia, päästöjen ulkoista validointia tai hyväksymistakuuta.",
  },
  cs: {
    labels: [
      "Rychlé rozhodnutí",
      "Potvrďte s příjemcem",
      "Nevhodné",
      "Důležité upřesnění",
      "Dokument připravený k odeslání.",
      "Zobrazit úplnou metodiku",
      "89 € za orientační CO₂e potvrzení",
      "Za dokument · bez předplatného",
      "Co zahrnuje 89 €",
      "Potřebujete více dokumentů?",
      "Otázky před objednávkou",
      "Údaje, obsah dokumentu, balíčky a podpora před objednávkou.",
      "Pochybnosti před platbou?",
      "Kontakt",
      "Jak funguje výpočet",
      "Zobrazit cenu",
      "Číst průvodce pro MSP →",
      "Připomenutí rozsahu",
      "Soukromí →",
      "Nahoru",
      "Úvod",
      "Vytvořit",
      "Pevná cena 89 €",
      "Bez předplatného",
      "Standardizované PDF",
      "Ověřitelné ID",
      "Není audit / není CSRD",
      "Před objednávkou a po ní",
    ],
    suitable: [
      "Zákazník žádá jednoduchou uhlíkovou informaci",
      "Dodavatelská platforma žádá dokument CO₂e",
      "Banka žádá uhlíkovou nebo ESG informaci",
      "Pojišťovna žádá environmentální informaci",
      "Výběrové řízení nepředepisuje metodu",
    ],
    exclusions: [
      "Je vyžadován úplný uhlíkový audit",
      "Je předepsána konkrétní norma nebo metoda",
      "Jsou vyžadovány podrobné Scope 1, 2 a 3",
      "Externí ověření je povinné",
      "Je vyžadováno vykazování CSRD / ESRS",
    ],
    questions: [
      "Je to vhodné pro můj požadavek?",
      "Jaké údaje mám připravit?",
      "Co dostanu za 89 €?",
      "Jaká metoda a koeficienty se používají?",
      "Mohu poslat stejné PDF více příjemcům?",
      "Jak fungují balíčky?",
      "Mohu opravit vydaný dokument?",
      "Co když stažení selže nebo PDF ztratím?",
      "Co potvrzuje dokumentární ověření?",
    ],
    packs:
      "Po potvrzení platby jsou klíče odeslány emailem. Každý klíč vytvoří jeden dokument a musí být použit do 365 dnů od vytvoření. Zadejte a ověřte klíč ve formuláři. Pokud email nedorazí, zkontrolujte spam a kontaktujte podporu bez dalšího nákupu.",
    correction:
      "Zkontrolujte údaje před platbou. Po vydání kontaktujte podporu s číslem objednávky a požadovanou opravou. Opětovné vydání není automaticky zdarma; podmínky se potvrdí před novou objednávkou.",
    download:
      "Zkuste to znovu na návratové stránce a kontaktujte podporu bez dalšího nákupu. Zkontrolujte doručovací email a spam. PDF ihned archivujte: Certif-Scope neuchovává obnovitelnou kopii. Při ztrátě kontaktujte podporu.",
    reuse:
      "Jednorázová platba za dokument, bez předplatného. DPH se neuplatňuje podle režimu vydavatele uvedeného v právních informacích. Stejné PDF lze poslat více příjemcům pro stejnou firmu, rok a údaje, pokud přijmou rozsah.",
    support:
      "Kontaktujte podporu při potížích se stažením, dotazech k objednávce nebo opravách. Opětovné vydání není automaticky zahrnuto; podmínky se potvrdí po posouzení. Cena nezahrnuje audit, externí validaci emisí ani záruku přijetí.",
  },
  sk: {
    labels: [
      "Rýchle rozhodnutie",
      "Potvrďte s príjemcom",
      "Nevhodné",
      "Dôležité upresnenie",
      "Dokument pripravený na odoslanie.",
      "Zobraziť úplnú metodiku",
      "89 € za orientačné CO₂e potvrdenie",
      "Za dokument · bez predplatného",
      "Čo zahŕňa 89 €",
      "Potrebujete viac dokumentov?",
      "Otázky pred objednávkou",
      "Údaje, obsah dokumentu, balíčky a podpora pred objednávkou.",
      "Pochybnosti pred platbou?",
      "Kontakt",
      "Ako funguje výpočet",
      "Zobraziť cenu",
      "Čítať príručku pre MSP →",
      "Pripomenutie rozsahu",
      "Súkromie →",
      "Nahor",
      "Úvod",
      "Vytvoriť",
      "Pevná cena 89 €",
      "Bez predplatného",
      "Štandardizované PDF",
      "Overiteľné ID",
      "Nie audit / nie CSRD",
      "Pred objednávkou a po nej",
    ],
    suitable: [
      "Zákazník žiada jednoduchú uhlíkovú informáciu",
      "Dodávateľská platforma žiada dokument CO₂e",
      "Banka žiada uhlíkovú alebo ESG informáciu",
      "Poisťovňa žiada environmentálnu informáciu",
      "Výberové konanie nepredpisuje metódu",
    ],
    exclusions: [
      "Vyžaduje sa úplný uhlíkový audit",
      "Je predpísaná konkrétna norma alebo metóda",
      "Vyžadujú sa podrobné Scope 1, 2 a 3",
      "Externé overenie je povinné",
      "Vyžaduje sa vykazovanie CSRD / ESRS",
    ],
    questions: [
      "Je to vhodné pre moju požiadavku?",
      "Aké údaje mám pripraviť?",
      "Čo dostanem za 89 €?",
      "Aká metóda a koeficienty sa používajú?",
      "Môžem poslať rovnaké PDF viacerým príjemcom?",
      "Ako fungujú balíčky?",
      "Môžem opraviť vydaný dokument?",
      "Čo ak sťahovanie zlyhá alebo stratím PDF?",
      "Čo potvrdzuje dokumentárne overenie?",
    ],
    packs:
      "Po potvrdení platby sa kľúče odošlú emailom. Každý kľúč vytvorí jeden dokument a treba ho použiť do 365 dní od vytvorenia. Zadajte a overte kľúč vo formulári. Ak email nepríde, skontrolujte spam a kontaktujte podporu bez ďalšieho nákupu.",
    correction:
      "Skontrolujte údaje pred platbou. Po vydaní kontaktujte podporu s číslom objednávky a žiadanou opravou. Opätovné vydanie nie je automaticky zadarmo; podmienky sa potvrdia pred novou objednávkou.",
    download:
      "Skúste znova na návratovej stránke a kontaktujte podporu bez ďalšieho nákupu. Skontrolujte doručovací email a spam. PDF ihneď archivujte: Certif-Scope neuchováva obnoviteľnú kópiu. Pri strate kontaktujte podporu.",
    reuse:
      "Jednorazová platba za dokument, bez predplatného. DPH sa neuplatňuje podľa režimu vydavateľa v právnych informáciách. Rovnaké PDF možno poslať viacerým príjemcom pre rovnakú firmu, rok a údaje, ak prijmú rozsah.",
    support:
      "Kontaktujte podporu pri problémoch so sťahovaním, otázkach k objednávke alebo opravách. Opätovné vydanie nie je automaticky zahrnuté; podmienky sa potvrdia po posúdení. Cena nezahŕňa audit, externú validáciu emisií ani záruku prijatia.",
  },
  sl: {
    labels: [
      "Hitra odločitev",
      "Potrdite s prejemnikom",
      "Ni primerno",
      "Pomembno pojasnilo",
      "Dokument, pripravljen za pošiljanje.",
      "Oglejte si celotno metodologijo",
      "89 € za okvirno potrdilo CO₂e",
      "Na dokument · brez naročnine",
      "Kaj vključuje 89 €",
      "Potrebujete več dokumentov?",
      "Vprašanja pred naročilom",
      "Podatki, vsebina dokumenta, paketi in podpora pred naročilom.",
      "Dvom pred plačilom?",
      "Kontakt",
      "Razumevanje izračuna",
      "Oglejte si ceno",
      "Preberite vodnik za MSP →",
      "Opomnik o obsegu",
      "Zasebnost →",
      "Na vrh",
      "Domov",
      "Ustvari",
      "Fiksna cena 89 €",
      "Brez naročnine",
      "Standardiziran PDF",
      "Preverljiv ID",
      "Ni revizija / ni CSRD",
      "Pred in po naročilu",
    ],
    suitable: [
      "Stranka zahteva preproste informacije o ogljiku",
      "Platforma dobaviteljev zahteva dokument CO₂e",
      "Banka zahteva informacije o ogljiku ali ESG",
      "Zavarovalnica zahteva okoljske informacije",
      "Razpis ne predpisuje metode",
    ],
    exclusions: [
      "Zahtevana je popolna ogljična revizija",
      "Predpisan je poseben standard ali metoda",
      "Zahtevani so podrobni obsegi 1, 2 in 3",
      "Zunanje preverjanje je obvezno",
      "Zahtevano je poročanje CSRD / ESRS",
    ],
    questions: [
      "Je to primerno za mojo zahtevo?",
      "Katere podatke pripravim?",
      "Kaj prejmem za 89 €?",
      "Katera metoda in koeficienti se uporabljajo?",
      "Lahko isti PDF pošljem več prejemnikom?",
      "Kako delujejo paketi?",
      "Lahko popravim izdan dokument?",
      "Kaj če prenos ne uspe ali izgubim PDF?",
      "Kaj potrjuje dokumentarno preverjanje?",
    ],
    packs:
      "Po potrditvi plačila se ključi pošljejo po emailu. Vsak ključ ustvari en dokument in ga je treba uporabiti v 365 dneh od nastanka. Vnesite in preverite ključ v obrazcu. Če email ne prispe, preverite neželeno pošto in kontaktirajte podporo brez ponovnega nakupa.",
    correction:
      "Preverite podatke pred plačilom. Po izdaji kontaktirajte podporo s sklicem naročila in želenim popravkom. Ponovna izdaja ni samodejno brezplačna; pogoji se potrdijo pred novim naročilom.",
    download:
      "Poskusite znova na povratni strani in kontaktirajte podporo brez novega nakupa. Preverite dostavni email in neželeno pošto. PDF takoj shranite: Certif-Scope ne hrani obnovljive kopije. Ob izgubi kontaktirajte podporo.",
    reuse:
      "Enkratno plačilo na dokument, brez naročnine. DDV se ne uporablja po režimu izdajatelja v pravnih informacijah. Isti PDF lahko pošljete več prejemnikom za isto podjetje, leto in podatke, če sprejmejo obseg.",
    support:
      "Kontaktirajte podporo za težave s prenosom, vprašanja o naročilu ali popravke. Ponovna izdaja ni samodejno vključena; pogoji se potrdijo po pregledu. Cena ne vključuje revizije, zunanje potrditve emisij ali jamstva sprejetja.",
  },
  hr: {
    labels: [
      "Brza odluka",
      "Potvrdite s primateljem",
      "Nije prikladno",
      "Važno pojašnjenje",
      "Dokument spreman za slanje.",
      "Pogledajte cjelovitu metodologiju",
      "89 € za indikativnu potvrdu CO₂e",
      "Po dokumentu · bez pretplate",
      "Što uključuje 89 €",
      "Trebate više dokumenata?",
      "Pitanja prije narudžbe",
      "Podaci, sadržaj dokumenta, paketi i podrška prije narudžbe.",
      "Dvojbe prije plaćanja?",
      "Kontakt",
      "Razumijevanje izračuna",
      "Pogledajte cijenu",
      "Pročitajte vodič za MSP-ove →",
      "Podsjetnik na obuhvat",
      "Privatnost →",
      "Na vrh",
      "Početna",
      "Izradi",
      "Fiksna cijena 89 €",
      "Bez pretplate",
      "Standardizirani PDF",
      "Provjerljiv ID",
      "Nije audit / nije CSRD",
      "Prije i nakon narudžbe",
    ],
    suitable: [
      "Klijent traži jednostavne informacije o ugljiku",
      "Platforma dobavljača traži dokument CO₂e",
      "Banka traži informacije o ugljiku ili ESG-u",
      "Osiguravatelj traži okolišne informacije",
      "Natječaj ne propisuje metodu",
    ],
    exclusions: [
      "Potreban je potpuni ugljični audit",
      "Propisan je određeni standard ili metoda",
      "Potrebni su detaljni opsezi 1, 2 i 3",
      "Vanjska verifikacija je obvezna",
      "Potrebno je izvještavanje CSRD / ESRS",
    ],
    questions: [
      "Je li prikladno za moj zahtjev?",
      "Koje podatke trebam pripremiti?",
      "Što dobivam za 89 €?",
      "Koja metoda i koeficijenti se koriste?",
      "Mogu li isti PDF poslati više primatelja?",
      "Kako funkcioniraju paketi?",
      "Mogu li ispraviti izdani dokument?",
      "Što ako preuzimanje ne uspije ili izgubim PDF?",
      "Što potvrđuje dokumentacijska provjera?",
    ],
    packs:
      "Nakon potvrde plaćanja ključevi se šalju emailom. Svaki ključ izrađuje jedan dokument i treba ga upotrijebiti u 365 dana od izrade. Unesite i provjerite ključ u obrascu. Ako email ne stigne, provjerite neželjenu poštu i kontaktirajte podršku bez ponovne kupnje.",
    correction:
      "Provjerite podatke prije plaćanja. Nakon izdavanja kontaktirajte podršku s referencom narudžbe i traženim ispravkom. Ponovno izdavanje nije automatski besplatno; uvjeti se potvrđuju prije nove narudžbe.",
    download:
      "Pokušajte ponovno sa stranice povratka i kontaktirajte podršku bez nove kupnje. Provjerite email dostave i neželjenu poštu. Odmah spremite PDF: Certif-Scope ne čuva obnovljivu kopiju. U slučaju gubitka kontaktirajte podršku.",
    reuse:
      "Jednokratno plaćanje po dokumentu, bez pretplate. PDV nije primjenjiv prema režimu izdavatelja navedenom u pravnim informacijama. Isti PDF može se slati više primatelja za istu tvrtku, godinu i podatke ako prihvaćaju obuhvat.",
    support:
      "Kontaktirajte podršku zbog problema s preuzimanjem, pitanja o narudžbi ili ispravaka. Ponovno izdavanje nije automatski uključeno; uvjeti se potvrđuju nakon pregleda. Cijena ne uključuje audit, vanjsku validaciju emisija niti jamstvo prihvaćanja.",
  },
  hu: {
    labels: [
      "Gyors döntés",
      "Egyeztesse a címzettel",
      "Nem megfelelő",
      "Fontos pontosítás",
      "Küldésre kész dokumentum.",
      "A teljes módszertan megtekintése",
      "89 € az indikatív CO₂e-igazolásért",
      "Dokumentumonként · előfizetés nélkül",
      "Mit tartalmaz a 89 €",
      "Több dokumentumra van szüksége?",
      "Kérdések a megrendelés előtt",
      "Adatok, dokumentumtartalom, csomagok és támogatás a rendeléshez.",
      "Bizonytalan a fizetés előtt?",
      "Kapcsolat",
      "A számítás megértése",
      "Ár megtekintése",
      "A kkv-útmutató elolvasása →",
      "Az alkalmazási kör összefoglalása",
      "Adatvédelem →",
      "Vissza a tetejére",
      "Kezdőlap",
      "Létrehozás",
      "Fix ár 89 €",
      "Előfizetés nélkül",
      "Szabványosított PDF",
      "Ellenőrizhető azonosító",
      "Nem audit / nem CSRD",
      "Megrendelés előtt és után",
    ],
    suitable: [
      "Az ügyfél egyszerű karboninformációt kér",
      "A beszállítói platform CO₂e-dokumentumot kér",
      "A bank karbon- vagy ESG-információt kér",
      "A biztosító környezeti információt kér",
      "A pályázat nem ír elő módszert",
    ],
    exclusions: [
      "Teljes karbonaudit szükséges",
      "Meghatározott szabvány vagy módszer kötelező",
      "Részletes Scope 1, 2 és 3 szükséges",
      "Külső ellenőrzés kötelező",
      "CSRD / ESRS-jelentés szükséges",
    ],
    questions: [
      "Megfelel az igényemnek?",
      "Milyen adatokat készítsek elő?",
      "Mit kapok 89 €-ért?",
      "Milyen módszert és együtthatókat használnak?",
      "Elküldhetem ugyanazt a PDF-et több címzettnek?",
      "Hogyan működnek a csomagok?",
      "Javítható a kiadott dokumentum?",
      "Mi a teendő, ha a letöltés sikertelen vagy elveszett a PDF?",
      "Mit igazol a dokumentumellenőrzés?",
    ],
    packs:
      "A fizetés visszaigazolása után a kulcsokat emailben küldjük. Egy kulcs egy dokumentumot hoz létre, és a létrehozástól számított 365 napon belül használható. Adja meg és ellenőrizze a kulcsot az űrlapon. Hiányzó email esetén ellenőrizze a spamet és keresse a támogatást új vásárlás nélkül.",
    correction:
      "Fizetés előtt ellenőrizze az adatokat. Kiadás után keresse a támogatást a rendelési hivatkozással és a kívánt javítással. Az újrakiadás nem automatikusan ingyenes; a feltételeket új rendelés előtt egyeztetjük.",
    download:
      "Próbálja újra a visszatérési oldalon, majd keresse a támogatást új vásárlás nélkül. Ellenőrizze a kézbesítési emailt és a spamet. Azonnal mentse a PDF-et: a Certif-Scope nem őriz visszaállítható másolatot. Elvesztés esetén keresse a támogatást.",
    reuse:
      "Egyszeri fizetés dokumentumonként, előfizetés nélkül. Az áfa a kibocsátó jogi tájékoztatásban szereplő adózási rendszere szerint nem alkalmazandó. Azonos cég, év és adatok esetén ugyanaz a PDF több címzettnek küldhető, ha elfogadják az alkalmazási kört.",
    support:
      "Letöltési problémák, rendelési kérdések vagy javítások esetén keresse a támogatást. Az újrakiadás nem automatikusan része az árnak; a feltételeket áttekintés után egyeztetjük. Az ár nem tartalmaz auditot, külső kibocsátás-validálást vagy elfogadási garanciát.",
  },
  bg: {
    labels: [
      "Бързо решение",
      "Потвърдете с получателя",
      "Неподходящо",
      "Важно уточнение",
      "Документ, готов за изпращане.",
      "Вижте пълната методика",
      "89 € за ориентировъчно удостоверение CO₂e",
      "За документ · без абонамент",
      "Какво включват 89 €",
      "Нужни са ви няколко документа?",
      "Въпроси преди поръчката",
      "Данни, съдържание на документа, пакети и поддръжка преди поръчка.",
      "Съмнения преди плащане?",
      "Контакт",
      "Как работи изчислението",
      "Вижте цената",
      "Прочетете ръководството за МСП →",
      "Напомняне за обхвата",
      "Поверителност →",
      "Нагоре",
      "Начало",
      "Създай",
      "Фиксирана цена 89 €",
      "Без абонамент",
      "Стандартизиран PDF",
      "Проверим ID",
      "Не е одит / не е CSRD",
      "Преди и след поръчката",
    ],
    suitable: [
      "Клиент иска проста информация за въглерода",
      "Платформа за доставчици иска CO₂e документ",
      "Банка иска информация за въглерод или ESG",
      "Застраховател иска екологична информация",
      "Търг не предписва методика",
    ],
    exclusions: [
      "Изисква се пълен въглероден одит",
      "Изисква се конкретен стандарт или метод",
      "Изискват се подробни обхвати 1, 2 и 3",
      "Външната проверка е задължителна",
      "Изисква се отчет CSRD / ESRS",
    ],
    questions: [
      "Подходящо ли е за моята заявка?",
      "Какви данни да подготвя?",
      "Какво получавам за 89 €?",
      "Какъв метод и коефициенти се използват?",
      "Мога ли да изпратя същия PDF на няколко получатели?",
      "Как работят пакетите?",
      "Мога ли да поправя издаден документ?",
      "Какво да правя при неуспешно изтегляне или загуба на PDF?",
      "Какво потвърждава документалната проверка?",
    ],
    packs:
      "След потвърждение на плащането ключовете се изпращат по email. Всеки ключ създава един документ и трябва да се използва до 365 дни от създаването. Въведете и проверете ключа във формуляра. Ако email не пристигне, проверете спама и се свържете с поддръжката без повторна покупка.",
    correction:
      "Проверете данните преди плащане. След издаване се свържете с поддръжката с номера на поръчката и исканата поправка. Преиздаването не е автоматично безплатно; условията се потвърждават преди нова поръчка.",
    download:
      "Опитайте отново от страницата за връщане и се свържете с поддръжката без нова покупка. Проверете email за доставка и спама. Запазете PDF веднага: Certif-Scope не съхранява възстановимо копие. При загуба се свържете с поддръжката.",
    reuse:
      "Еднократно плащане за документ, без абонамент. ДДС не се прилага според режима на издателя в правната информация. Същият PDF може да се изпрати на няколко получатели за същата фирма, година и данни, ако приемат обхвата.",
    support:
      "Свържете се с поддръжката при проблем с изтеглянето, въпрос за поръчката или поправки. Преиздаването не е включено автоматично; условията се потвърждават след преглед. Цената не включва одит, външно валидиране на емисиите или гаранция за приемане.",
  },
  el: {
    labels: [
      "Γρήγορη απόφαση",
      "Επιβεβαιώστε με τον παραλήπτη",
      "Δεν είναι κατάλληλο",
      "Σημαντική διευκρίνιση",
      "Ένα έγγραφο έτοιμο για αποστολή.",
      "Δείτε την πλήρη μεθοδολογία",
      "89 € για την ενδεικτική βεβαίωση CO₂e",
      "Ανά έγγραφο · χωρίς συνδρομή",
      "Τι περιλαμβάνουν τα 89 €",
      "Χρειάζεστε πολλά έγγραφα;",
      "Ερωτήσεις πριν την παραγγελία",
      "Δεδομένα, περιεχόμενο εγγράφου, πακέτα και υποστήριξη πριν την παραγγελία.",
      "Αμφιβολίες πριν την πληρωμή;",
      "Επικοινωνία",
      "Κατανόηση του υπολογισμού",
      "Δείτε την τιμή",
      "Διαβάστε τον οδηγό ΜΜΕ →",
      "Υπενθύμιση πεδίου",
      "Απόρρητο →",
      "Επιστροφή στην κορυφή",
      "Αρχική",
      "Δημιουργία",
      "Σταθερή τιμή 89 €",
      "Χωρίς συνδρομή",
      "Τυποποιημένο PDF",
      "Επαληθεύσιμο ID",
      "Όχι έλεγχος / όχι CSRD",
      "Πριν και μετά την παραγγελία",
    ],
    suitable: [
      "Πελάτης ζητά απλές πληροφορίες άνθρακα",
      "Πλατφόρμα προμηθευτών ζητά έγγραφο CO₂e",
      "Τράπεζα ζητά πληροφορίες άνθρακα ή ESG",
      "Ασφαλιστής ζητά περιβαλλοντικές πληροφορίες",
      "Διαγωνισμός δεν επιβάλλει μέθοδο",
    ],
    exclusions: [
      "Απαιτείται πλήρης έλεγχος άνθρακα",
      "Επιβάλλεται συγκεκριμένο πρότυπο ή μέθοδος",
      "Απαιτούνται αναλυτικά Scope 1, 2 και 3",
      "Η εξωτερική επαλήθευση είναι υποχρεωτική",
      "Απαιτείται αναφορά CSRD / ESRS",
    ],
    questions: [
      "Είναι κατάλληλο για το αίτημά μου;",
      "Ποια δεδομένα πρέπει να ετοιμάσω;",
      "Τι λαμβάνω για 89 €;",
      "Ποια μέθοδος και συντελεστές χρησιμοποιούνται;",
      "Μπορώ να στείλω το ίδιο PDF σε πολλούς παραλήπτες;",
      "Πώς λειτουργούν τα πακέτα;",
      "Μπορώ να διορθώσω εκδοθέν έγγραφο;",
      "Τι κάνω αν αποτύχει η λήψη ή χάσω το PDF;",
      "Τι επιβεβαιώνει η τεκμηριωτική επαλήθευση;",
    ],
    packs:
      "Μετά την επιβεβαίωση πληρωμής, τα κλειδιά αποστέλλονται με email. Κάθε κλειδί δημιουργεί ένα έγγραφο και χρησιμοποιείται εντός 365 ημερών από τη δημιουργία. Εισάγετε και ελέγξτε το κλειδί στη φόρμα. Ελέγξτε τα ανεπιθύμητα και επικοινωνήστε με την υποστήριξη αν λείπει το email, χωρίς νέα αγορά.",
    correction:
      "Ελέγξτε τα δεδομένα πριν πληρώσετε. Μετά την έκδοση, επικοινωνήστε με την υποστήριξη με την αναφορά παραγγελίας και τη ζητούμενη διόρθωση. Η επανέκδοση δεν είναι αυτόματα δωρεάν· οι όροι επιβεβαιώνονται πριν από νέα παραγγελία.",
    download:
      "Δοκιμάστε ξανά από τη σελίδα επιστροφής και επικοινωνήστε με την υποστήριξη χωρίς νέα αγορά. Ελέγξτε το email παράδοσης και τα ανεπιθύμητα. Αποθηκεύστε το PDF αμέσως: η Certif-Scope δεν διατηρεί ανακτήσιμο αντίγραφο. Σε απώλεια, επικοινωνήστε με την υποστήριξη.",
    reuse:
      "Εφάπαξ πληρωμή ανά έγγραφο, χωρίς συνδρομή. Ο ΦΠΑ δεν εφαρμόζεται βάσει του καθεστώτος του εκδότη στις νομικές πληροφορίες. Το ίδιο PDF μπορεί να σταλεί σε πολλούς παραλήπτες για την ίδια εταιρεία, έτος και δεδομένα, εφόσον αποδέχονται το πεδίο.",
    support:
      "Επικοινωνήστε με την υποστήριξη για προβλήματα λήψης, ερωτήσεις παραγγελίας ή διορθώσεις. Η επανέκδοση δεν περιλαμβάνεται αυτόματα· οι όροι επιβεβαιώνονται μετά την εξέταση. Η τιμή δεν περιλαμβάνει έλεγχο, εξωτερική επικύρωση εκπομπών ή εγγύηση αποδοχής.",
  },
  et: {
    labels: [
      "Kiire otsus",
      "Kinnitage saajaga",
      "Ei sobi",
      "Oluline täpsustus",
      "Saatmiseks valmis dokument.",
      "Vaadake täielikku metoodikat",
      "89 € indikatiivse CO₂e-tõendi eest",
      "Dokumendi kohta · tellimuseta",
      "Mida 89 € sisaldab",
      "Vajate mitut dokumenti?",
      "Küsimused enne tellimist",
      "Andmed, dokumendi sisu, paketid ja tugi enne tellimist.",
      "Kahtlused enne maksmist?",
      "Kontakt",
      "Arvutuse selgitus",
      "Vaadake hinda",
      "Lugege VKE juhendit →",
      "Ulatus meeldetuletuseks",
      "Privaatsus →",
      "Üles",
      "Avaleht",
      "Loo",
      "Fikseeritud hind 89 €",
      "Tellimuseta",
      "Standardiseeritud PDF",
      "Kontrollitav ID",
      "Ei ole audit / ei ole CSRD",
      "Enne ja pärast tellimust",
    ],
    suitable: [
      "Klient küsib lihtsat süsinikuteavet",
      "Tarnijaplatvorm küsib CO₂e-dokumenti",
      "Pank küsib süsiniku- või ESG-teavet",
      "Kindlustaja küsib keskkonnateavet",
      "Hange ei määra meetodit",
    ],
    exclusions: [
      "Nõutakse täielikku süsinikuauditit",
      "Kindel standard või meetod on kohustuslik",
      "Nõutakse üksikasjalikke Scope 1, 2 ja 3",
      "Väline kontroll on kohustuslik",
      "Nõutakse CSRD / ESRS-aruannet",
    ],
    questions: [
      "Kas see sobib minu vajadusele?",
      "Millised andmed ette valmistada?",
      "Mida saan 89 € eest?",
      "Millist meetodit ja koefitsiente kasutatakse?",
      "Kas võin saata sama PDF-i mitmele saajale?",
      "Kuidas paketid toimivad?",
      "Kas väljastatud dokumenti saab parandada?",
      "Mida teha, kui allalaadimine nurjub või PDF kaob?",
      "Mida kinnitab dokumendikontroll?",
    ],
    packs:
      "Pärast makse kinnitamist saadetakse võtmed emailiga. Iga võti loob ühe dokumendi ja tuleb kasutada 365 päeva jooksul loomisest. Sisestage ja kontrollige võtit vormil. Kui email puudub, kontrollige rämpsposti ja võtke toega ühendust ilma uuesti ostmata.",
    correction:
      "Kontrollige andmeid enne makset. Pärast väljastamist võtke toega ühendust tellimuse viite ja soovitud parandusega. Uuesti väljastamine pole automaatselt tasuta; tingimused kinnitatakse enne uut tellimust.",
    download:
      "Proovige uuesti tagasilehel ja võtke toega ühendust ilma uuesti ostmata. Kontrollige tarneemaili ja rämpsposti. Salvestage PDF kohe: Certif-Scope ei säilita taastatavat koopiat. Kaotuse korral võtke toega ühendust.",
    reuse:
      "Ühekordne makse dokumendi kohta, tellimuseta. Käibemaks ei kohaldu väljastaja õiguslikus teabes märgitud maksurežiimi järgi. Sama PDF-i võib saata sama ettevõtte, aasta ja andmete puhul mitmele saajale, kui nad ulatuse aktsepteerivad.",
    support:
      "Võtke toega ühendust allalaadimisprobleemide, tellimusküsimuste või paranduste korral. Uuesti väljastamine ei kuulu automaatselt hinna sisse; tingimused kinnitatakse pärast läbivaatamist. Hind ei sisalda auditit, heitmete välist valideerimist ega aktsepteerimise garantiid.",
  },
  lv: {
    labels: [
      "Ātrs lēmums",
      "Apstipriniet ar saņēmēju",
      "Nav piemērots",
      "Svarīgs precizējums",
      "Dokuments gatavs nosūtīšanai.",
      "Skatīt pilnu metodoloģiju",
      "89 € par indikatīvu CO₂e apliecinājumu",
      "Par dokumentu · bez abonementa",
      "Ko ietver 89 €",
      "Vajadzīgi vairāki dokumenti?",
      "Jautājumi pirms pasūtījuma",
      "Dati, dokumenta saturs, komplekti un atbalsts pirms pasūtījuma.",
      "Šaubas pirms maksāšanas?",
      "Kontakti",
      "Izprast aprēķinu",
      "Skatīt cenu",
      "Lasīt MVU rokasgrāmatu →",
      "Tvēruma atgādinājums",
      "Privātums →",
      "Uz augšu",
      "Sākums",
      "Izveidot",
      "Fiksēta cena 89 €",
      "Bez abonementa",
      "Standartizēts PDF",
      "Pārbaudāms ID",
      "Nav audits / nav CSRD",
      "Pirms un pēc pasūtījuma",
    ],
    suitable: [
      "Klients pieprasa vienkāršu oglekļa informāciju",
      "Piegādātāju platforma pieprasa CO₂e dokumentu",
      "Banka pieprasa oglekļa vai ESG informāciju",
      "Apdrošinātājs pieprasa vides informāciju",
      "Iepirkums nenosaka metodiku",
    ],
    exclusions: [
      "Nepieciešams pilns oglekļa audits",
      "Obligāts konkrēts standarts vai metode",
      "Nepieciešami detalizēti Scope 1, 2 un 3",
      "Ārēja pārbaude ir obligāta",
      "Nepieciešams CSRD / ESRS ziņojums",
    ],
    questions: [
      "Vai tas atbilst manam pieprasījumam?",
      "Kādi dati jāsagatavo?",
      "Ko saņemu par 89 €?",
      "Kāda metode un koeficienti tiek izmantoti?",
      "Vai varu nosūtīt to pašu PDF vairākiem saņēmējiem?",
      "Kā darbojas komplekti?",
      "Vai varu labot izdotu dokumentu?",
      "Ko darīt, ja lejupielāde neizdodas vai PDF pazūd?",
      "Ko apstiprina dokumentārā pārbaude?",
    ],
    packs:
      "Pēc maksājuma apstiprināšanas atslēgas nosūta pa emailu. Katra atslēga izveido vienu dokumentu un jāizmanto 365 dienās pēc izveides. Ievadiet un pārbaudiet atslēgu veidlapā. Ja emails nav saņemts, pārbaudiet surogātpastu un sazinieties ar atbalstu bez atkārtota pirkuma.",
    correction:
      "Pārbaudiet datus pirms maksāšanas. Pēc izdošanas sazinieties ar atbalstu, norādot pasūtījuma atsauci un vēlamo labojumu. Atkārtota izdošana nav automātiski bez maksas; nosacījumus apstiprina pirms jauna pasūtījuma.",
    download:
      "Mēģiniet vēlreiz atgriešanās lapā un sazinieties ar atbalstu bez jauna pirkuma. Pārbaudiet piegādes emailu un surogātpastu. Saglabājiet PDF uzreiz: Certif-Scope neglabā atjaunojamu kopiju. Zaudējuma gadījumā sazinieties ar atbalstu.",
    reuse:
      "Vienreizējs maksājums par dokumentu, bez abonementa. PVN nepiemēro saskaņā ar izdevēja režīmu juridiskajā informācijā. To pašu PDF var nosūtīt vairākiem saņēmējiem par to pašu uzņēmumu, gadu un datiem, ja tie pieņem tvērumu.",
    support:
      "Sazinieties ar atbalstu lejupielādes problēmu, pasūtījuma jautājumu vai labojumu gadījumā. Atkārtota izdošana nav automātiski iekļauta; nosacījumus apstiprina pēc pārskatīšanas. Cena neietver auditu, emisiju ārēju validāciju vai pieņemšanas garantiju.",
  },
  lt: {
    labels: [
      "Greitas sprendimas",
      "Patvirtinkite su gavėju",
      "Netinka",
      "Svarbus paaiškinimas",
      "Dokumentas paruoštas siųsti.",
      "Peržiūrėti visą metodiką",
      "89 € už orientacinę CO₂e pažymą",
      "Už dokumentą · be prenumeratos",
      "Ką apima 89 €",
      "Reikia kelių dokumentų?",
      "Klausimai prieš užsakymą",
      "Duomenys, dokumento turinys, paketai ir pagalba prieš užsakymą.",
      "Abejojate prieš mokėdami?",
      "Kontaktai",
      "Suprasti skaičiavimą",
      "Žiūrėti kainą",
      "Skaityti MVĮ vadovą →",
      "Apimties priminimas",
      "Privatumas →",
      "Į viršų",
      "Pradžia",
      "Sukurti",
      "Fiksuota kaina 89 €",
      "Be prenumeratos",
      "Standartizuotas PDF",
      "Patikrinamas ID",
      "Ne auditas / ne CSRD",
      "Prieš ir po užsakymo",
    ],
    suitable: [
      "Klientas prašo paprastos anglies informacijos",
      "Tiekėjų platforma prašo CO₂e dokumento",
      "Bankas prašo anglies ar ESG informacijos",
      "Draudikas prašo aplinkos informacijos",
      "Konkursas nenustato metodikos",
    ],
    exclusions: [
      "Reikalingas išsamus anglies auditas",
      "Privalomas konkretus standartas ar metodas",
      "Reikalingos išsamios Scope 1, 2 ir 3",
      "Išorinis tikrinimas privalomas",
      "Reikalinga CSRD / ESRS ataskaita",
    ],
    questions: [
      "Ar tai tinka mano užklausai?",
      "Kokius duomenis paruošti?",
      "Ką gaunu už 89 €?",
      "Kokia metodika ir koeficientai naudojami?",
      "Ar galiu tą patį PDF siųsti keliems gavėjams?",
      "Kaip veikia paketai?",
      "Ar galiu pataisyti išduotą dokumentą?",
      "Ką daryti, jei atsisiuntimas nepavyksta ar prarandu PDF?",
      "Ką patvirtina dokumentinis tikrinimas?",
    ],
    packs:
      "Patvirtinus mokėjimą, raktai siunčiami emailu. Kiekvienas raktas sukuria vieną dokumentą ir turi būti panaudotas per 365 dienas nuo sukūrimo. Įveskite ir patikrinkite raktą formoje. Jei emailas neateina, patikrinkite šlamštą ir kreipkitės į pagalbą nepirkdami dar kartą.",
    correction:
      "Patikrinkite duomenis prieš mokėjimą. Po išdavimo kreipkitės į pagalbą su užsakymo nuoroda ir norimu pataisymu. Pakartotinis išdavimas nėra automatiškai nemokamas; sąlygos patvirtinamos prieš naują užsakymą.",
    download:
      "Bandykite dar kartą grįžimo puslapyje ir kreipkitės į pagalbą nepirkdami iš naujo. Patikrinkite pristatymo emailą ir šlamštą. Iškart išsaugokite PDF: Certif-Scope nelaiko atkuriamos kopijos. Praradę kreipkitės į pagalbą.",
    reuse:
      "Vienkartinis mokėjimas už dokumentą, be prenumeratos. PVM netaikomas pagal išdavėjo režimą teisinėje informacijoje. Tą patį PDF galima siųsti keliems gavėjams tai pačiai įmonei, metams ir duomenims, jei jie priima apimtį.",
    support:
      "Kreipkitės į pagalbą dėl atsisiuntimo, užsakymo klausimų ar pataisymų. Pakartotinis išdavimas automatiškai neįtrauktas; sąlygos patvirtinamos peržiūrėjus. Kaina neapima audito, išorinio emisijų patvirtinimo ar priėmimo garantijos.",
  },
  ga: {
    labels: [
      "Cinneadh tapa",
      "Deimhnigh leis an bhfaighteoir",
      "Níl sé oiriúnach",
      "Soiléiriú tábhachtach",
      "Doiciméad réidh le seoladh.",
      "Féach an mhodheolaíocht iomlán",
      "89 € ar do dheimhniú táscach CO₂e",
      "In aghaidh an doiciméid · gan síntiús",
      "Cad atá san áireamh ar 89 €",
      "An bhfuil roinnt doiciméad uait?",
      "Ceisteanna roimh ordú",
      "Sonraí, ábhar an doiciméid, pacáistí agus tacaíocht roimh ordú.",
      "Amhras roimh íocaíocht?",
      "Teagmháil",
      "An ríomh a thuiscint",
      "Féach an praghas",
      "Léigh treoir na FBManna →",
      "Meabhrúchán ar an raon",
      "Príobháideachas →",
      "Ar ais go barr",
      "Baile",
      "Cruthaigh",
      "Praghas socraithe 89 €",
      "Gan síntiús",
      "PDF caighdeánaithe",
      "ID infhíoraithe",
      "Ní iniúchadh / ní CSRD",
      "Roimh agus i ndiaidh d’ordaithe",
    ],
    suitable: [
      "Iarrann cliant faisnéis shimplí charbóin",
      "Iarrann ardán soláthraithe doiciméad CO₂e",
      "Iarrann banc faisnéis charbóin nó ESG",
      "Iarrann árachóir faisnéis chomhshaoil",
      "Ní fhorordaíonn tairiscint modh",
    ],
    exclusions: [
      "Tá iniúchadh iomlán carbóin de dhíth",
      "Tá caighdeán nó modh sonrach éigeantach",
      "Tá Scóip 1, 2 agus 3 mhionsonraithe de dhíth",
      "Tá fíorú seachtrach éigeantach",
      "Tá tuairisciú CSRD / ESRS de dhíth",
    ],
    questions: [
      "An oireann sé do m’iarratas?",
      "Cad iad na sonraí ba cheart dom a ullmhú?",
      "Cad a fhaighim ar 89 €?",
      "Cén modh agus comhéifeachtaí a úsáidtear?",
      "An féidir liom an PDF céanna a sheoladh chuig roinnt faighteoirí?",
      "Conas a oibríonn na pacáistí?",
      "An féidir doiciméad eisithe a cheartú?",
      "Cad má theipeann ar an íoslódáil nó má chaillim an PDF?",
      "Cad a dheimhníonn fíorú doiciméadach?",
    ],
    packs:
      "Seoltar na heochracha trí email tar éis dearbhú íocaíochta. Cruthaíonn gach eochair doiciméad amháin agus caithfear í a úsáid laistigh de 365 lá óna cruthú. Cuir isteach agus seiceáil an eochair san fhoirm. Seiceáil turscar agus déan teagmháil le tacaíocht mura dtagann an email, gan ceannach arís.",
    correction:
      "Seiceáil na sonraí roimh íocaíocht. Tar éis eisiúna, déan teagmháil le tacaíocht leis an tagairt ordaithe agus an ceartú atá ag teastáil. Ní bhíonn atheisiúint saor go huathoibríoch; dearbhaítear na coinníollacha roimh ordú nua.",
    download:
      "Bain triail eile as ar an leathanach fillte agus déan teagmháil le tacaíocht gan ceannach arís. Seiceáil an email seachadta agus turscar. Sábháil an PDF láithreach: ní choinníonn Certif-Scope cóip inaisghabhála. Déan teagmháil le tacaíocht má chailltear é.",
    reuse:
      "Íocaíocht aonuaire in aghaidh an doiciméid, gan síntiús. Ní bhaineann CBL leis faoi chóras an eisitheora sa bhfaisnéis dhlíthiúil. Is féidir an PDF céanna a sheoladh chuig roinnt faighteoirí don chuideachta, bliain agus sonraí céanna má ghlacann siad leis an raon.",
    support:
      "Déan teagmháil le tacaíocht faoi fhadhbanna íoslódála, ceisteanna ordaithe nó ceartuithe. Ní chuirtear atheisiúint san áireamh go huathoibríoch; dearbhaítear coinníollacha tar éis athbhreithnithe. Ní chuimsíonn an praghas iniúchadh, bailíochtú seachtrach astaíochtaí ná ráthaíocht ghlactha.",
  },
  mt: {
    labels: [
      "Deċiżjoni malajr",
      "Ikkonferma mar-riċevitur",
      "Mhux adattat",
      "Kjarifika importanti",
      "Dokument lest biex jintbagħat.",
      "Ara l-metodoloġija sħiħa",
      "89 € għall-attestazzjoni indikattiva CO₂e",
      "Għal kull dokument · mingħajr abbonament",
      "X’jinkludu d-89 €",
      "Għandek bżonn diversi dokumenti?",
      "Mistoqsijiet qabel l-ordni",
      "Dejta, kontenut tad-dokument, pakketti u appoġġ qabel l-ordni.",
      "Dubju qabel il-ħlas?",
      "Kuntatt",
      "Ifhem il-kalkolu",
      "Ara l-prezz",
      "Aqra l-gwida għall-SMEs →",
      "Tfakkira tal-ambitu",
      "Privatezza →",
      "Lura fuq",
      "Paġna ewlenija",
      "Oħloq",
      "Prezz fiss 89 €",
      "Mingħajr abbonament",
      "PDF standardizzat",
      "ID verifikabbli",
      "Mhux awditu / mhux CSRD",
      "Qabel u wara l-ordni",
    ],
    suitable: [
      "Klijent jitlob informazzjoni sempliċi dwar il-karbonju",
      "Pjattaforma ta’ fornituri titlob dokument CO₂e",
      "Bank jitlob informazzjoni dwar il-karbonju jew ESG",
      "Assiguratur jitlob informazzjoni ambjentali",
      "Sejħa għall-offerti ma timponix metodu",
    ],
    exclusions: [
      "Jinħtieġ awditu sħiħ tal-karbonju",
      "Standard jew metodu speċifiku huwa obbligatorju",
      "Jinħtieġu Scope 1, 2 u 3 dettaljati",
      "Verifika esterna hija obbligatorja",
      "Jinħtieġ rapport CSRD / ESRS",
    ],
    questions: [
      "Huwa adattat għat-talba tiegħi?",
      "Liema dejta għandi nipprepara?",
      "X’nirċievi għal 89 €?",
      "Liema metodu u koeffiċjenti jintużaw?",
      "Nista’ nibgħat l-istess PDF lil diversi riċevituri?",
      "Kif jaħdmu l-pakketti?",
      "Nista’ nikkoreġi dokument maħruġ?",
      "X’nagħmel jekk it-tniżżil ifalli jew nitlef il-PDF?",
      "X’tikkonferma l-verifika dokumentarja?",
    ],
    packs:
      "Wara konferma tal-ħlas, iċ-ċwievet jintbagħtu b’email. Kull ċavetta toħloq dokument wieħed u trid tintuża fi żmien 365 jum mill-ħolqien. Daħħal u vverifika ċ-ċavetta fil-formola. Jekk l-email ma tasalx, iċċekkja l-ispam u kkuntattja l-appoġġ mingħajr ma tixtri mill-ġdid.",
    correction:
      "Iċċekkja d-dejta qabel tħallas. Wara l-ħruġ, ikkuntattja l-appoġġ bir-referenza tal-ordni u l-korrezzjoni mitluba. Ħruġ mill-ġdid mhuwiex awtomatikament b’xejn; il-kundizzjonijiet jiġu kkonfermati qabel ordni ġdida.",
    download:
      "Erġa’ pprova mill-paġna tar-ritorn u kkuntattja l-appoġġ mingħajr xiri ġdid. Iċċekkja l-email tal-kunsinna u l-ispam. Issejvja l-PDF minnufih: Certif-Scope ma żżommx kopja li tista’ tiġi rkuprata. Jekk jintilef, ikkuntattja l-appoġġ.",
    reuse:
      "Ħlas wieħed għal kull dokument, mingħajr abbonament. Il-VAT mhix applikabbli skont ir-reġim tal-emittent fl-informazzjoni legali. L-istess PDF jista’ jintbagħat lil diversi riċevituri għall-istess kumpanija, sena u dejta jekk jaċċettaw l-ambitu.",
    support:
      "Ikkuntattja l-appoġġ għal problemi ta’ tniżżil, mistoqsijiet dwar l-ordni jew korrezzjonijiet. Ħruġ mill-ġdid mhux awtomatikament inkluż; il-kundizzjonijiet jiġu kkonfermati wara reviżjoni. Il-prezz ma jinkludix awditu, validazzjoni esterna tal-emissjonijiet jew garanzija ta’ aċċettazzjoni.",
  },
};

// Legal/help destinations exist in English for non-core languages. Keep real
// destinations rather than linking to nonexistent translated secondary pages.
export const HOME_LEGAL_LABELS: Record<EuNonCoreLocale, string[]> = {
  es: [
    "Aviso legal",
    "Condiciones de uso",
    "Cookies",
    "Tratamiento de datos",
    "Colaboraciones",
    "Accesos rápidos",
    "Casos de uso",
    "Guías",
    "Empresa y legal",
    "Información",
    "Todos los derechos reservados.",
    "Menú de navegación",
  ],
  it: [
    "Note legali",
    "Condizioni d’uso",
    "Cookie",
    "Trattamento dei dati",
    "Collaborazioni",
    "Accessi rapidi",
    "Casi d’uso",
    "Guide",
    "Azienda e informazioni legali",
    "Informazioni",
    "Tutti i diritti riservati.",
    "Menu di navigazione",
  ],
  pl: [
    "Informacje prawne",
    "Warunki użytkowania",
    "Pliki cookie",
    "Przetwarzanie danych",
    "Partnerstwa",
    "Szybki dostęp",
    "Przykłady zastosowań",
    "Poradniki",
    "Firma i prawo",
    "Informacje",
    "Wszelkie prawa zastrzeżone.",
    "Menu nawigacji",
  ],
  nl: [
    "Juridische informatie",
    "Gebruiksvoorwaarden",
    "Cookies",
    "Gegevensverwerking",
    "Partnerschappen",
    "Snelle toegang",
    "Toepassingen",
    "Gidsen",
    "Bedrijf en juridisch",
    "Informatie",
    "Alle rechten voorbehouden.",
    "Navigatiemenu",
  ],
  pt: [
    "Informação legal",
    "Condições de utilização",
    "Cookies",
    "Tratamento de dados",
    "Parcerias",
    "Acessos rápidos",
    "Casos de uso",
    "Guias",
    "Empresa e informação legal",
    "Informação",
    "Todos os direitos reservados.",
    "Menu de navegação",
  ],
  ro: [
    "Informații juridice",
    "Condiții de utilizare",
    "Cookie-uri",
    "Prelucrarea datelor",
    "Parteneriate",
    "Acces rapid",
    "Cazuri de utilizare",
    "Ghiduri",
    "Companie și informații juridice",
    "Informații",
    "Toate drepturile rezervate.",
    "Meniu de navigare",
  ],
  sv: [
    "Juridisk information",
    "Användarvillkor",
    "Kakor",
    "Databehandling",
    "Partnerskap",
    "Snabblänkar",
    "Användningsfall",
    "Guider",
    "Företag och juridik",
    "Information",
    "Alla rättigheter förbehållna.",
    "Navigeringsmeny",
  ],
  da: [
    "Juridiske oplysninger",
    "Brugsvilkår",
    "Cookies",
    "Databehandling",
    "Partnerskaber",
    "Hurtig adgang",
    "Anvendelser",
    "Guider",
    "Virksomhed og jura",
    "Information",
    "Alle rettigheder forbeholdes.",
    "Navigationsmenu",
  ],
  fi: [
    "Oikeudelliset tiedot",
    "Käyttöehdot",
    "Evästeet",
    "Tietojenkäsittely",
    "Kumppanuudet",
    "Pikalinkit",
    "Käyttötapaukset",
    "Oppaat",
    "Yritys ja oikeudelliset tiedot",
    "Tiedot",
    "Kaikki oikeudet pidätetään.",
    "Navigointivalikko",
  ],
  cs: [
    "Právní informace",
    "Podmínky použití",
    "Cookies",
    "Zpracování údajů",
    "Partnerství",
    "Rychlé odkazy",
    "Příklady použití",
    "Průvodci",
    "Společnost a právo",
    "Informace",
    "Všechna práva vyhrazena.",
    "Navigační nabídka",
  ],
  sk: [
    "Právne informácie",
    "Podmienky používania",
    "Cookies",
    "Spracovanie údajov",
    "Partnerstvá",
    "Rýchle odkazy",
    "Príklady použitia",
    "Príručky",
    "Spoločnosť a právo",
    "Informácie",
    "Všetky práva vyhradené.",
    "Navigačná ponuka",
  ],
  sl: [
    "Pravne informacije",
    "Pogoji uporabe",
    "Piškotki",
    "Obdelava podatkov",
    "Partnerstva",
    "Hitre povezave",
    "Primeri uporabe",
    "Vodniki",
    "Podjetje in pravo",
    "Informacije",
    "Vse pravice pridržane.",
    "Navigacijski meni",
  ],
  hr: [
    "Pravne informacije",
    "Uvjeti korištenja",
    "Kolačići",
    "Obrada podataka",
    "Partnerstva",
    "Brze poveznice",
    "Primjeri primjene",
    "Vodiči",
    "Tvrtka i pravne informacije",
    "Informacije",
    "Sva prava pridržana.",
    "Navigacijski izbornik",
  ],
  hu: [
    "Jogi tájékoztatás",
    "Felhasználási feltételek",
    "Sütik",
    "Adatkezelés",
    "Partnerségek",
    "Gyorshivatkozások",
    "Felhasználási esetek",
    "Útmutatók",
    "Cég és jogi információk",
    "Információk",
    "Minden jog fenntartva.",
    "Navigációs menü",
  ],
  bg: [
    "Правна информация",
    "Условия за ползване",
    "Бисквитки",
    "Обработка на данни",
    "Партньорства",
    "Бързи връзки",
    "Примери за употреба",
    "Ръководства",
    "Фирма и право",
    "Информация",
    "Всички права запазени.",
    "Навигационно меню",
  ],
  el: [
    "Νομικές πληροφορίες",
    "Όροι χρήσης",
    "Cookies",
    "Επεξεργασία δεδομένων",
    "Συνεργασίες",
    "Γρήγορη πρόσβαση",
    "Περιπτώσεις χρήσης",
    "Οδηγοί",
    "Εταιρεία και νομικά",
    "Πληροφορίες",
    "Με επιφύλαξη παντός δικαιώματος.",
    "Μενού πλοήγησης",
  ],
  et: [
    "Õigusteave",
    "Kasutustingimused",
    "Küpsised",
    "Andmetöötlus",
    "Partnerlused",
    "Kiirlingid",
    "Kasutusjuhud",
    "Juhendid",
    "Ettevõte ja õigus",
    "Teave",
    "Kõik õigused kaitstud.",
    "Navigeerimismenüü",
  ],
  lv: [
    "Juridiskā informācija",
    "Lietošanas noteikumi",
    "Sīkdatnes",
    "Datu apstrāde",
    "Partnerības",
    "Ātrās saites",
    "Lietošanas piemēri",
    "Rokasgrāmatas",
    "Uzņēmums un tiesības",
    "Informācija",
    "Visas tiesības aizsargātas.",
    "Navigācijas izvēlne",
  ],
  lt: [
    "Teisinė informacija",
    "Naudojimo sąlygos",
    "Slapukai",
    "Duomenų tvarkymas",
    "Partnerystės",
    "Greitos nuorodos",
    "Naudojimo atvejai",
    "Vadovai",
    "Įmonė ir teisė",
    "Informacija",
    "Visos teisės saugomos.",
    "Naršymo meniu",
  ],
  ga: [
    "Faisnéis dhlíthiúil",
    "Téarmaí úsáide",
    "Fianáin",
    "Próiseáil sonraí",
    "Comhpháirtíochtaí",
    "Naisc thapa",
    "Cásanna úsáide",
    "Treoracha",
    "Cuideachta agus dlí",
    "Faisnéis",
    "Gach ceart ar cosaint.",
    "Roghchlár nascleanúna",
  ],
  mt: [
    "Informazzjoni legali",
    "Termini tal-użu",
    "Cookies",
    "Ipproċessar tad-dejta",
    "Sħubijiet",
    "Links ta’ malajr",
    "Każijiet ta’ użu",
    "Gwidi",
    "Kumpanija u legali",
    "Informazzjoni",
    "Id-drittijiet kollha riżervati.",
    "Menu tan-navigazzjoni",
  ],
};

export const PERSONALIZED_PDF: Record<EuNonCoreLocale, string> = {
  bg: "Персонализиран PDF на името на вашата фирма",
  hr: "Personalizirani PDF na ime vaše tvrtke",
  cs: "Personalizované PDF se jménem vaší firmy",
  da: "En personlig PDF med din virksomheds navn",
  nl: "Een gepersonaliseerde PDF op naam van uw bedrijf",
  et: "Teie ettevõtte nimega isikupärastatud PDF",
  fi: "Yrityksesi nimellä personoitu PDF",
  el: "Εξατομικευμένο PDF στο όνομα της εταιρείας σας",
  hu: "Személyre szabott PDF a vállalkozása nevére",
  ga: "PDF pearsantaithe in ainm do chuideachta",
  it: "Un PDF personalizzato a nome della vostra azienda",
  lv: "Personalizēts PDF uz jūsu uzņēmuma vārda",
  lt: "Individualizuotas PDF jūsų įmonės vardu",
  mt: "PDF personalizzat f’isem il-kumpanija tiegħek",
  pl: "Spersonalizowany PDF z nazwą Twojej firmy",
  pt: "Um PDF personalizado em nome da sua empresa",
  ro: "Un PDF personalizat pe numele companiei dvs.",
  sk: "Personalizované PDF s názvom vašej firmy",
  sl: "Prilagojen PDF z imenom vašega podjetja",
  es: "Un PDF personalizado a nombre de su empresa",
  sv: "En personlig PDF i ditt företags namn",
};
