"use client";

export default function Section10() {
  return (
    <section
      id="s10"
      className="scroll-mt-24 border-b border-gray-200 pb-24"
    >

      {/* HEADER — Institutional */}
      <div className="p-12 bg-[#F8FAFC] border border-gray-300 dark:border-gray-700 dark:bg-gray-900 rounded-2xl shadow-lg relative overflow-hidden">
        <h2 className="text-4xl md:text-5xl font-extrabold text-[#0B3A63]">
          10. Liability Framework & Legal Responsibilities
        </h2>

        <p className="text-lg text-gray-700 dark:text-gray-300 max-w-5xl mt-6 leading-relaxed">
          This section defines the legal responsibility boundaries associated with Certif-Scope
          outputs and clarifies the obligations of all involved parties. The attestation is an
          indicative CO₂e result derived from user-provided expenditure data and must not be
          interpreted as audited emissions, environmental certification, or a substitute for
          regulatory reporting. Liability is strictly limited to deterministic computation using
          the inputs supplied by the user.
        </p>
      </div>



      {/* BLOCK — Legal Nature of the Attestation */}
      <div className="mt-16 p-10 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-xl shadow-md">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Legal Nature of the Attestation
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
          The CO₂e attestation generated by Certif-Scope is not an environmental certificate,
          not a compliance report, and not an audited measure. It is a deterministic calculation
          based solely on:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          <li>• user-submitted expenditure data,</li>
          <li>• published category definitions,</li>
          <li>• a fixed emission-factor dataset version.</li>
        </ul>
      </div>



      {/* BLOCK — Responsibility Allocation */}
      <div className="mt-20 p-10 bg-[#F8FAFC] dark:bg-gray-900 border border-[#15B097]/30 dark:border-gray-700 rounded-xl shadow-sm">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Responsibility Allocation Between Parties
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 mb-4 leading-relaxed max-w-5xl">
          Responsibilities are clearly separated to avoid misinterpretation:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed max-w-5xl">
          <li>• The user is responsible for the accuracy and completeness of financial inputs.</li>
          <li>• Certif-Scope is responsible for deterministic processing of validated values.</li>
          <li>• Third-party reviewers are responsible for independent verification of the computation.</li>
          <li>• No party may extend the attestation’s meaning beyond its defined scope.</li>
        </ul>
      </div>



      {/* BLOCK — Liability Exclusions */}
      <div className="mt-20 p-10 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-xl shadow-md">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Explicit Liability Exclusions
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed mb-4">
          Certif-Scope does not assume liability for interpretations or uses outside the strictly
          defined methodology. Explicit exclusions include:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          <li>• No guarantee regarding accuracy of user data.</li>
          <li>• No validation of supplier-specific carbon performance.</li>
          <li>• No compliance guarantee for CSRD, ESRS, EU Taxonomy or ISO audits.</li>
          <li>• No suitability for regulatory fines mitigation or legal defence.</li>
          <li>• No verification of operational emissions (Scope 1/2/3 activity-based).</li>
        </ul>
      </div>



      {/* BLOCK — Prohibited Legal Interpretations */}
      <div className="mt-20 p-10 bg-[#F8FAFC] dark:bg-gray-900 border border-[#15B097]/30 dark:border-gray-700 rounded-xl shadow-sm">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Prohibited Legal Interpretations
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 mb-4 leading-relaxed max-w-5xl">
          The CO₂e attestation must not be interpreted as:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed max-w-5xl">
          <li>• proof of real emissions,</li>
          <li>• environmental certification or compliance approval,</li>
          <li>• confirmation of supplier ESG performance,</li>
          <li>• a guarantee of completeness or data accuracy,</li>
          <li>• a substitute for mandatory disclosures under EU regulation.</li>
        </ul>
      </div>



      {/* BLOCK — Institutional Safeguards */}
      <div className="mt-20 p-10 bg-[#0B3A63] text-white rounded-xl shadow-md relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#15B097]/20 to-transparent opacity-20 pointer-events-none"></div>

        <h3 className="text-2xl font-semibold relative z-10">
          Institutional Safeguards
        </h3>

        <p className="mt-4 text-white/90 text-sm leading-relaxed max-w-5xl relative z-10">
          To avoid misuse by institutions or third parties, the attestation embeds a legal
          disclaimer and version metadata. It explicitly states that results are indicative,
          non-binding, and not validated against physical operations or real-world emissions.
        </p>
      </div>



      {/* RETURN BUTTON */}
      <div className="mt-12 text-right">
        <a
          href="#top"
          className="inline-block text-sm px-4 py-2 rounded-md border border-[#0B3A63] text-[#0B3A63] hover:bg-[#0B3A63] hover:text-white transition-colors"
        >
          Back to summary
        </a>
      </div>

    </section>
  );
      }
