"use client";

export default function Section7() {
  return (
    <section
      id="s7"
      className="scroll-mt-24 border-b border-gray-200 pb-24"
    >

      {/* HEADER */}
      <div className="p-12 bg-[#F8FAFC] border border-gray-300 dark:border-gray-700 dark:bg-gray-900 rounded-2xl shadow-lg">
        <h2 className="text-4xl md:text-5xl font-extrabold text-[#0B3A63]">
          7. Prohibited Claims & Misuse Prevention
        </h2>

        <p className="text-lg text-gray-700 dark:text-gray-300 max-w-5xl mt-6 leading-relaxed">
          This section establishes strict prohibitions to prevent misinterpretation,
          regulatory misalignment or unlawful communication of results. Certif-Scope
          values are indicative only and cannot be used for advertising, compliance
          filings, public ESG declarations or comparative performance benchmarking.
        </p>
      </div>



      {/* BLOCK — Forbidden Communication Uses */}
      <div className="mt-16 p-10 bg-white dark:bg-gray-800 rounded-xl border border-gray-300 dark:border-gray-700 shadow-md">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Forbidden Use in External Communications
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 max-w-5xl leading-relaxed mb-4">
          Under EU consumer law and environmental marketing regulations, the values
          generated by Certif-Scope must not be presented in any context implying
          verified or certified emissions performance:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          <li>• No ESG marketing claims or promotional statements.</li>
          <li>• No “carbon neutral”, “low carbon”, or similar claims.</li>
          <li>• No public comparison against competitors or industry averages.</li>
          <li>• No use in product environmental labeling or eco-design compliance.</li>
          <li>• No publication as audited or regulator-approved data.</li>
        </ul>
      </div>



      {/* BLOCK — Regulatory Misuse Restrictions */}
      <div className="mt-20 p-10 bg-[#F8FAFC] dark:bg-gray-900 rounded-xl border border-[#15B097]/30 dark:border-gray-700 shadow-sm">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Prohibited Regulatory Misuse
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 mb-4 leading-relaxed max-w-5xl">
          Certif-Scope output must not be submitted, referenced or implied in any legal,
          contractual or regulatory document requiring validated emissions accounting:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
          <li>• Not acceptable for CSRD or ESRS filings.</li>
          <li>• Not acceptable for ISO 14064-1 verification.</li>
          <li>• Not acceptable for EU Taxonomy classification.</li>
          <li>• Not acceptable for EU Green Claims Directive compliance.</li>
          <li>• Not acceptable for national regulatory emissions registries.</li>
        </ul>
      </div>



      {/* BLOCK — Legal Risk Prevention */}
      <div className="mt-20 p-10 bg-white dark:bg-gray-800 rounded-xl border border-gray-300 dark:border-gray-700 shadow-md">
        <h3 className="text-2xl font-semibold text-[#0B3A63] mb-4">
          Legal Risk Prevention
        </h3>

        <p className="text-sm text-gray-700 dark:text-gray-300 max-w-5xl leading-relaxed mb-4">
          Institutions must ensure that indicative values are not reinterpreted as
          factual emissions. Misrepresentation can trigger legal liabilities under:
        </p>

        <ul className="space-y-2 text-sm text-gray-700 dark:text-gray-300 max-w-5xl leading-relaxed">
          <li>• EU Unfair Commercial Practices Directive (for misleading claims).</li>
          <li>• National consumer protection and advertising laws.</li>
          <li>• Banking and procurement due diligence misreporting risks.</li>
          <li>• Contractual liability for inaccurate ESG disclosures.</li>
        </ul>
      </div>



      {/* BLOCK — Why Prohibited Claims Matter */}
      <div className="mt-20 p-10 bg-[#0B3A63] text-white rounded-xl shadow-md relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-[#15B097]/25 to-transparent opacity-20 pointer-events-none"></div>

        <h3 className="text-2xl font-semibold relative z-10">
          Why These Prohibitions Are Required
        </h3>

        <p className="mt-4 text-white/90 max-w-5xl leading-relaxed relative z-10">
          Without explicit restrictions, indicative values could be misrepresented as 
          regulatory-grade data, exposing institutions to compliance breaches, sanctions 
          or reputational risk. These prohibitions ensure legal clarity, protect users, 
          and preserve the methodological integrity of spend-based estimations.
        </p>
      </div>



      {/* RETURN BUTTON */}
      <div className="mt-12 text-right">
        <a
          href="#top"
          className="inline-block text-sm px-4 py-2 rounded-md border border-[#0B3A63] text-[#0B3A63] hover:bg-[#0B3A63] hover:text-white transition-colors"
        >
          Back to summary
        </a>
      </div>

    </section>
  );
    }
