import { NextResponse } from "next/server";
import puppeteer from "puppeteer-core";

export async function POST(req: Request) {
  try {
    const data = await req.json();

    const {
      companyName,
      sector,
      country,
      period,
      scope1,
      scope2,
      scope3,
      total,
    } = data;

    const browserlessKey = process.env.BROWSERLESS_KEY;

    if (!browserlessKey) {
      return NextResponse.json(
        { error: "Missing BROWSERLESS_KEY" },
        { status: 500 }
      );
    }

    const html = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Certif-Scope CO₂e Attestation</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      color: #0B3A63;
      padding: 40px;
      font-size: 14px;
    }
    h1 {
      font-size: 22px;
      margin-bottom: 5px;
    }
    .subtitle {
      color: #15B097;
      font-weight: bold;
      margin-bottom: 30px;
    }
    .section {
      margin-bottom: 16px;
    }
    .label {
      font-weight: bold;
    }
    .box {
      border: 1px solid #e5e7eb;
      padding: 16px;
      border-radius: 6px;
      margin-top: 12px;
    }
    .total {
      font-weight: bold;
      margin-top: 10px;
    }
    footer {
      margin-top: 40px;
      font-size: 11px;
      color: #6b7280;
    }
  </style>
</head>
<body>

  <h1>CO₂e Attestation</h1>
  <div class="subtitle">Certif-Scope — Indicative Attestation</div>

  <div class="section"><span class="label">Company:</span> ${companyName}</div>
  <div class="section"><span class="label">Sector:</span> ${sector}</div>
  <div class="section"><span class="label">Country:</span> ${country}</div>
  <div class="section"><span class="label">Reporting period:</span> ${period}</div>

  <div class="box">
    <div>Scope 1: ${scope1} tCO₂e</div>
    <div>Scope 2: ${scope2} tCO₂e</div>
    <div>Scope 3: ${scope3} tCO₂e</div>
    <div class="total">Total: ${total} tCO₂e</div>
  </div>

  <footer>
    This document is generated automatically using a spend-based indicative methodology.
    It is not an audit and is not CSRD / ESRS compliant.
    Generated by Certif-Scope.
  </footer>

</body>
</html>
`;

    const browser = await puppeteer.connect({
      browserWSEndpoint: `wss://chrome.browserless.io?token=${browserlessKey}`,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "networkidle0" });

    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
    });

    await page.close();
    await browser.close();

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          'attachment; filename="certif-scope-attestation.pdf"',
      },
    });
  } catch (err: any) {
    return NextResponse.json(
      { error: "PDF generation error", message: err.message },
      { status: 500 }
    );
  }
}
