"use client";
import Image from "next/image";

export default function AttestationPreview() {
  return (
    <section className="py-24 bg-[#F8FAFC] dark:bg-gray-900">
      <div className="max-w-6xl mx-auto px-6 text-center">

        <p className="text-xs md:text-sm font-medium text-gray-500 dark:text-gray-400 tracking-wider uppercase mb-3">
          CO₂e Attestation Preview — Standardized • Spend-Based • Verifiable
        </p>

        <div className="w-16 h-[2px] bg-gray-300 dark:bg-gray-700 mx-auto mb-8" />

        <h2 className="text-2xl md:text-3xl font-extrabold text-[#0B3A63] dark:text-gray-100 leading-tight mb-6">
          The Exact CO₂e Attestation Generated by Certif-Scope
        </h2>

        <p className="text-base md:text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed mb-16">
          A clear spend-based CO₂e Attestation including total emissions, category breakdown,
          dataset version, timestamp and a unique verification ID.  
          Structured specifically for supplier onboarding, procurement documentation and
          banking or insurer screening workflows.
        </p>

        <div className="flex justify-center">
          <div className="relative w-full max-w-[600px]">
            <Image
              src="/preview.webp"
              alt="CO₂e Attestation preview"
              width={1200}
              height={800}
              loading="lazy"
              sizes="(max-width: 768px) 100vw, 600px"
              className="rounded-2xl shadow-xl border border-gray-200 dark:border-gray-700"
            />
          </div>
        </div>

        <div className="mt-12 flex flex-col items-center">
          <a
            href="/sample-pdf"
            className="px-10 py-4 rounded-xl bg-[#0B3A63] text-white font-semibold text-sm md:text-base hover:bg-[#083253] transition shadow-md"
          >
            Download Sample PDF
          </a>

          <p className="mt-4 text-xs text-gray-500 dark:text-gray-400 max-w-sm">
            Indicative, spend-based CO₂e document. Not a CSRD/ESRS report or audited inventory.
          </p>
        </div>

      </div>
    </section>
  );
}
