"use client";
import Image from "next/image";

export default function AttestationPreview() {
  return (
    <section className="py-20 bg-[#F8FAFC] dark:bg-gray-900">
      <div className="max-w-6xl mx-auto px-6 text-center">

        {/* SECTION LABEL */}
        <p className="text-xs md:text-sm font-medium text-gray-500 dark:text-gray-400 tracking-wider uppercase mb-3">
          CO₂e Attestation Preview • Instant • Spend-Based
        </p>

        <div className="w-16 h-[2px] bg-gray-300 dark:bg-gray-700 mx-auto mb-8" />

        {/* TITLE */}
        <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900 dark:text-gray-100 leading-tight mb-6">
          A Professional CO₂e Attestation Ready to Send Immediately
        </h2>

        {/* DESCRIPTION */}
        <p className="text-base md:text-lg text-gray-600 dark:text-gray-300 max-w-2xl mx-auto leading-relaxed mb-16">
          This is the exact standardized format generated by Certif-Scope.  
          A clear spend-based CO₂e Attestation including your indicators, category breakdown
          and a unique verification ID.  
          Designed for supplier onboarding, procurement documentation and banking requests.
          Not a regulatory or audited emissions report.
        </p>

        {/* IMAGE */}
        <div className="flex justify-center">
          <div className="relative w-full max-w-[600px]">
            <Image
              src="/preview.webp"
              alt="CO₂e Attestation preview"
              width={1200}
              height={800}
              loading="lazy"
              sizes="(max-width: 768px) 100vw, 600px"
              className="rounded-lg shadow-xl border border-gray-200 dark:border-gray-700"
            />
          </div>
        </div>

        {/* CTA + SUBTEXT */}
        <div className="mt-12 flex flex-col items-center">
          <a
            href="/sample-attestation.pdf"
            target="_blank"
            rel="noopener noreferrer"
            className="px-8 py-4 rounded-xl bg-[#0B3A63] text-white font-semibold text-sm md:text-base hover:bg-[#083253] transition shadow-md"
          >
            Download sample PDF
          </a>

          <p className="mt-4 text-xs text-gray-500 dark:text-gray-400 max-w-sm">
            Already used by SMEs across Europe to respond quickly and professionally to CO₂e
            information requests.
          </p>
        </div>

      </div>
    </section>
  );
}
