import Breadcrumb from "@/components/Common/Breadcrumb";

export default function RegulationsPage() {
  return (
    <>
      <Breadcrumb
        pageName="Regulations"
        description="Understanding the regulatory context, responsibilities and limitations of Certif-Scope CO₂ attestations."
      />

      {/* SECTION — Intro */}
      <section className="py-20 bg-white dark:bg-gray-900">
        <div className="max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-[#0B3A63] mb-6">
            Regulatory context
          </h2>

          <p className="text-gray-700 dark:text-gray-300 leading-relaxed">
            Certif-Scope provides an automated CO₂ estimation aligned with the 
            spend-based guidance of the Greenhouse Gas Protocol (Corporate Standard).
            It is designed to support internal reporting, procurement processes and 
            general environmental disclosures but does not constitute an accredited
            certification or a regulated environmental audit.
          </p>
        </div>
      </section>

      {/* SECTION — What Certif-Scope is not */}
      <section className="py-20 bg-[#F8FAFC] dark:bg-gray-800">
        <div className="max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-[#0B3A63] mb-6">
            What Certif-Scope does not provide
          </h2>

          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-10">
            To ensure clarity and regulatory transparency, it is important to state
            the boundaries of the service. Certif-Scope does not replace mandatory
            environmental audits or certifications when required by law.
          </p>

          <ul className="space-y-4 text-gray-700 dark:text-gray-300">
            <li>• Not a regulatory audit or certification</li>
            <li>• Not a verification of accounting records</li>
            <li>• Not a life-cycle analysis (LCA) assessment</li>
            <li>• Not a supplier-specific carbon evaluation</li>
            <li>• Not compliant for mandatory audited reports (CSRD/ESRS)</li>
          </ul>
        </div>
      </section>

      {/* SECTION — User responsibility */}
      <section className="py-20 bg-white dark:bg-gray-900">
        <div className="max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-[#0B3A63] mb-6">
            User responsibility
          </h2>

          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-6">
            The attestation generated by Certif-Scope is based entirely on 
            user-submitted financial information. Users retain full responsibility
            for the accuracy, completeness and truthfulness of the data entered.
          </p>

          <ul className="space-y-4 text-gray-700 dark:text-gray-300">
            <li>• All inputs are declared by the user</li>
            <li>• Certif-Scope does not check supporting documents</li>
            <li>• Users are accountable for data accuracy</li>
            <li>• Incorrect inputs produce incorrect estimates</li>
          </ul>
        </div>
      </section>

      {/* SECTION — Verification scope */}
      <section className="py-20 bg-[#F8FAFC] dark:bg-gray-800">
        <div className="max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-[#0B3A63] mb-6">
            Verification scope
          </h2>

          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-10">
            The verification identifier included in each attestation allows any 
            recipient to validate the integrity of the document. It confirms that 
            the content has not been modified since issuance.
          </p>

          <ul className="space-y-4 text-gray-700 dark:text-gray-300">
            <li>• Confirms document integrity</li>
            <li>• Detects modifications or tampering</li>
            <li>• Works without accessing Certif-Scope</li>
            <li>• Does not validate input accuracy</li>
          </ul>
        </div>
      </section>

      {/* SECTION — Institutional acceptance */}
      <section className="py-20 bg-white dark:bg-gray-900">
        <div className="max-w-5xl mx-auto px-6">
          <h2 className="text-3xl font-bold text-[#0B3A63] mb-6">
            Institutional acceptance
          </h2>

          <p className="text-gray-700 dark:text-gray-300 leading-relaxed mb-10">
            Many procurement teams, financial institutions and corporate partners
            accept spend-based CO₂ estimates as part of general environmental
            disclosures. However, acceptance always depends on the internal policies
            of the reviewing organization.
          </p>

          <ul className="space-y-4 text-gray-700 dark:text-gray-300">
            <li>• Acceptance varies by sector and institution</li>
            <li>• Some organizations require audited data</li>
            <li>• Certif-Scope provides indicative values, not audited ones</li>
            <li>• Users must verify suitability with their recipients</li>
          </ul>
        </div>
      </section>
    </>
  );
    }
