"use client";

import { useEffect } from "react";

/**
 * Certif-Scope public verification key (Ed25519)
 * Immutable public key used to verify all Certif-Scope attestations.
 *
 * Format: Base64-encoded DER (SPKI)
 */
const CERTIFSCOPE_PUBLIC_KEY_BASE64 = `
MCowBQYDK2VwAyEAbKp2pg4wmzE5Kqo9tEwv7JJjxQyT2cBmwiLLHp4cSac=
`.trim();

export default function VerifyPage() {
  useEffect(() => {
    // This page is intentionally informational only.
    // No automated or server-side verification is performed.
  }, []);

  return (
    <div className="max-w-6xl mx-auto px-6 pt-10 pb-24">
      {/* HEADER */}
      <header className="mb-12">
        <h1 className="text-3xl md:text-4xl font-extrabold text-[#0B3A63] mb-4">
          Verify a CO₂e Attestation
        </h1>

        <p className="text-lg text-gray-700 leading-relaxed max-w-3xl">
          This page explains how to independently verify the authenticity and
          integrity of a CO₂e attestation issued by Certif-Scope.
        </p>
      </header>

      {/* STEP 1 */}
      <section className="mb-10 max-w-3xl">
        <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
          1. Download the attestation PDF
        </h2>

        <p className="text-gray-700 leading-relaxed">
          The Certif-Scope attestation is a digitally signed PDF document.
          <strong> The PDF itself is the only verifiable object.</strong>
        </p>

        <p className="text-gray-700 leading-relaxed mt-3">
          If you arrived on this page by scanning a QR code, download the original
          PDF file that contains the attestation. Do not rely on screenshots or
          printed copies.
        </p>
      </section>

      {/* STEP 2 */}
      <section className="mb-10 max-w-3xl">
        <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
          2. What the PDF contains
        </h2>

        <p className="text-gray-700 leading-relaxed mb-3">
          Each Certif-Scope attestation PDF embeds the following elements:
        </p>

        <ul className="list-disc pl-6 text-gray-700 space-y-1">
          <li>A canonical signed data payload (fixed structure)</li>
          <li>A digital signature generated by Certif-Scope</li>
          <li>A unique Attestation ID printed on the document</li>
        </ul>
      </section>

      {/* STEP 3 */}
      <section className="mb-10 max-w-3xl">
        <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
          3. How to verify the attestation
        </h2>

        <p className="text-gray-700 leading-relaxed mb-4">
          To verify the attestation independently:
        </p>

        <ol className="list-decimal pl-6 text-gray-700 space-y-2">
          <li>Extract the signed payload and the digital signature from the PDF.</li>
          <li>
            Verify the signature using the Certif-Scope public verification key
            shown below.
          </li>
          <li>
            Confirm that the Attestation ID printed on the document matches the
            Attestation ID contained in the signed payload.
          </li>
        </ol>

        <p className="text-gray-700 leading-relaxed mt-4">
          If the signature verification succeeds and the document content has not
          been altered, the attestation is authentic.
        </p>
      </section>

      {/* PRACTICAL EXAMPLE */}
      <section className="mb-12 max-w-3xl">
        <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
          Practical verification example (technical)
        </h2>

        <p className="text-gray-700 leading-relaxed mb-3">
          Below is an illustrative example for technical reviewers (banks,
          auditors, IT teams). Other tools or programming languages may also be
          used.
        </p>

        <pre className="text-sm bg-white border border-gray-300 rounded-md p-4 overflow-x-auto mb-4">
{`# Example workflow (illustrative)
# 1. Extract payload.json and signature.b64 from the PDF
# 2. Decode the signature
base64 -d signature.b64 > signature.bin

# 3. Verify the signature using the public key
# (public key converted to PEM format beforehand)
openssl pkeyutl \\
  -verify \\
  -pubin \\
  -inkey certif-scope-public.pem \\
  -rawin \\
  -in payload.json \\
  -sigfile signature.bin`}
        </pre>

        <p className="text-gray-700 leading-relaxed">
          If the verification command succeeds, the document has not been altered
          and was issued by Certif-Scope.
        </p>
      </section>

      {/* PUBLIC KEY */}
      <section className="mb-12 max-w-3xl">
        <h2 className="text-xl font-bold text-[#0B3A63] mb-3">
          Certif-Scope public verification key
        </h2>

        <p className="text-gray-700 leading-relaxed mb-3">
          The following public key is used to verify the digital signature of all
          Certif-Scope attestations.
        </p>

        <pre className="text-sm bg-white border border-gray-300 rounded-md p-4 overflow-x-auto">
{CERTIFSCOPE_PUBLIC_KEY_BASE64}
        </pre>

        <p className="mt-3 text-sm text-gray-600">
          Algorithm: Ed25519<br />
          This public key is permanent and does not change.
        </p>
      </section>

      {/* IMPORTANT NOTICE */}
      <div className="max-w-3xl text-sm text-gray-600 leading-relaxed">
        <p>
          <strong>Important notice.</strong> This page does not perform automated
          verification and does not validate user-provided data. It provides
          instructions for independent verification only.
        </p>

        <p className="mt-3">
          Certif-Scope attestations are indicative, spend-based CO₂e estimates.
          They do not constitute an audit, certification, regulatory compliance
          (including CSRD or ESRS), or assurance engagement.
        </p>
      </div>
    </div>
  );
      }
